recurly/recurly-client-dotnet

History.md
Library/Invoice.cs

Add OriginalInvoiceNumber to refund invoices

---

Library/Extensions/XmlWriterExtensions.cs
Library/List/RecurlyList.cs
Library/List/SubscriptionAddOnList.cs

fixes https://github.com/recurly/recurly-client-net/issues/62
cc/ @austinheap

Clear subscription addons if there are none in the list

---

History.md
Library/Adjustment.cs

fixes https://github.com/recurly/recurly-client-net/issues/29
cc/ @bhelx 
test:
- Find a plan's invoice
```c#
var invoice = Invoices.Get(<invoice_number>);
Console.WriteLine(invoice.Adjustments[0].ProductCode);
```

Product code on adjustment

---

History.md
Library/Transaction.cs

cc/ @bhelx 
tests:
- the following should create a tax exempt transaction
```c#
var transaction = new Transaction("<accountCode>", 1000, "USD");
transaction.TaxExempt = true;
transaction.Create();
Console.WriteLine(transaction.Uuid);
```

Add TaxExempt, TaxCode, AccountingCode to Transaction

---

Library/Account.cs
Library/Error.cs
Library/Subscription.cs
README.md

Updating all links that referenced the old docs url.
Before: https://docs.recurly.com/api
After: https://dev.recurly.com
cc: @bhelx

Updating docs links

---

History.md
Library/Coupon.cs

**Description**:
Add support for new coupon duration attributes (duration, temporal_unit, temporal_amount)
**Additional approvers**:
@bhelx
**Testing**:
- Verify that new coupons can be created with duration=forever/single_use/temporal, single_use=true, & applies_for_months=n
- Verify that when reading all of the created coupons the values for duration, temporal_unit, temporal_amount, single_use, & applies_for_months are all correct
```
var coupon = new_coupon();
coupon.Duration = Coupon.CouponDuration.Forever;
coupon.Create();
coupon = Coupons.Get(coupon.CouponCode);
Console.WriteLine("duration: " + coupon.Duration);
Console.WriteLine("temporal_unit: " + coupon.TemporalUnit);
Console.WriteLine("temporal_amount: " + coupon.TemporalAmount);
Console.WriteLine("applies_for_months: " + …
```

adding support for new coupon duration attributes

---

History.md
Library/Properties/AssemblyInfo.cs

Bumping to version 1.2.3
This version contains fix for broken subscription preview response.

bump_1_2_3

---

History.md
Library/Account.cs
Library/CouponRedemption.cs

Allows us to redeem a coupon for a specific subscription uuid.
Approvers: @cbarton 
```csharp
var account = Accounts.Get("myaccount");
// should be a subscription level coupon
// should also allow us to leave the subscriptionUuid blank
var redemption = account.RedeemCoupon("mysubcoupon", "USD", "30f4ffc2ee6f5ed67232574f9f8dad0d");
Console.WriteLine(redemption);
```

Subscription level coupon redemption

---

Library/CouponRedemption.cs
Library/List/CouponRedemptionList.cs
Library/Subscription.cs

Trying to fix. Seems to only be reading one element right now.
Approvers: @cbarton
```csharp
var sub = Subscriptions.Get("308d1f45319d5ae8cb15b742f194114c");
var redemptions = sub.GetRedemptions();
Console.WriteLine(redemptions);
Console.WriteLine(redemptions.Count);
Console.WriteLine(redemptions[0].AccountCode);
```

Add GetRedemptions to Subscription

---

Library/BillingInfo.cs

Do not include billing info in request if a token is present

---

Library/Client.cs
Library/Coupon.cs
Library/List/CouponList.cs
Library/List/RecurlyList.cs

Adding support for bulk coupons and generating unique coupons.
```csharp
var coupon = Coupons.Get("mybulkcoupon");
var coupons = coupon.Generate(5);
// You may optionally choose to fetch and work with the items
coupons.GetItems();
foreach (Coupon c in coupons) {
Console.WriteLine(c.CouponCode);
}
```

Bulk and Unique coupons

---

History.md
Library/Coupon.cs

Adding support to edit and restore coupons.
* Get a coupon and edit it
```csharp
var coupon = Coupons.Get("special");
coupon.Name = "My New Coupon Name";
coupon.Update();
```
* Get an expired coupon and restore / edit it
```csharp
var coupon = Coupons.Get("expired");
coupon.Name = "My New Coupon Name";
coupon.Restore();
```

Edit and Restore Coupons

---

History.md
Library/Properties/AssemblyInfo.cs

Bumping to version 1.2.5
* added; multiple redemption support `GetRedemptions` for `Invoice` https://github.com/recurly/recurly-client-net/pull/105
* added; description readers to `Coupon` ReadXml https://github.com/recurly/recurly-client-net/pull/111
* added; `PreviewChange` method for `Subscription` https://github.com/recurly/recurly-client-net/pull/116
* added; `Update()` and `Restore()` paths to `Coupon` https://github.com/recurly/recurly-client-net/pull/109
* added; Bulk and Unique Coupons support https://github.com/recurly/recurly-client-net/pull/108
* added; Coupon default to SingleCode https://github.com/recurly/recurly-client-net/pull/120

Bumping to 1.2.5

---

Library/Subscription.cs

```csharp
Subscription sub = Subscriptions.Get("3280d5e063b2a307d66287416db538af");
Console.WriteLine(sub.RemainingBillingCycles);
```

adds RemainingBillingCycles to retrieved Subscription object

---

History.md
Library/Subscription.cs
README.md

* Updating the History file
* Updating the README with info on .NET targets

Update history and readme

---

History.md
Library/Properties/AssemblyInfo.cs

Bump to 1.3.1

---

Library/Subscription.cs

Avoids unnecessary api calls when only the subscriptions plan code is required.

Exposed subscription 'PlanCode' publicly 

---

Library/Adjustment.cs
Library/Coupon.cs
Test/AdjustmentTest.cs

Fixed Get Adjustment and related test

---

Library/AddOn.cs
Library/Configuration/Settings.cs
Library/List/MeasuredUnitList.cs
Library/MeasuredUnit.cs
Library/Recurly.csproj
Library/Usage.cs

https://docs.recurly.com/docs/usage-based-billing
```csharp
String unit = Guid.NewGuid().ToString().Replace("-", "");
String planCode = Guid.NewGuid().ToString().Replace("-", "");
String accountCode = Guid.NewGuid().ToString().Replace("-", "");
Console.WriteLine(accountCode);
var measuredUnit = new MeasuredUnit(unit, "Marketing Email", "A Marketing email sent by customer");
measuredUnit.Create();
//var id = measuredUnit.Id;
//measuredUnit.Description = "A new description";
//measuredUnit.Update();
//Console.WriteLine(measuredUnit);
//Console.WriteLine(MeasuredUnits.Get(id));
// will be removed from usage but you can still get to it with the id
//measuredUnit.Delete()
// plancode, description
var plan = new Plan(planCode, "my new plan")
{
PlanIntervalLength = 1,
PlanIntervalUnit = …
```

Usage Based Billing Support

---

Library/Usage.cs

Attempts to fix issue https://github.com/recurly/recurly-client-net/issues/168

Do not parse nil usage_percentage

---

History.md
Library/Properties/AssemblyInfo.cs

* Do not parse nil `usage_percentage` #169

Bump 1.4.1

---

History.md
Library/Subscription.cs

Add SubscriptionState.Failed

---

Library/Account.cs
Library/Configuration/Settings.cs
Library/List/ShippingAddressList.cs
Library/Recurly.csproj
Library/ShippingAddress.cs
Library/Subscription.cs

This is still a work in progress. It will allow a few features:
* Linking multiple shipping addresses with an account
* Creating a subscription with an associated shipping address
```csharp
String accountCode = Guid.NewGuid().ToString().Replace("-", "");
var account = new Account(accountCode);
ShippingAddress shad = new ShippingAddress();
shad.Nickname = "bhelx";
shad.Address1 = "400 Alabama St";
shad.City = "San Francisco";
shad.Zip = "94110";
shad.Country = "US";
shad.CompanyName = "Recurly Inc";
shad.FirstName = "Benjamin";
shad.LastName = "Person";
account.ShippingAddresses.Add(shad);
ShippingAddress shad2 = new ShippingAddress();
shad2.Nickname = "sharky";
shad2.Address1 = "643 Magazine St";
shad2.City = "New Orleans";
shad2.Zip = "70115";
shad2.Country = "US";
shad2.CompanyName = …
```

Shipping Addresses

---

Library/Coupon.cs

Resolves #180 
* Added a new constructor `Coupon(String code, String name, CouponDiscountType discountType)`
* Made sure `discount_percentage` was optionally parseable
* Added `FreeTrial*` attributes
```csharp
// construct a free trial coupon
// I've added this new constructor
var coupon = new Coupon("coupon1234", "coupon1234", Coupon.CouponDiscountType.FreeTrial);
// set the free trial to 10 days
coupon.FreeTrialAmount = 10;
coupon.FreeTrialUnit = Coupon.CouponTemporalUnit.Day;
coupon.Create();
Console.WriteLine(coupon);
Console.WriteLine(coupon.FreeTrialAmount.ToString());
Console.WriteLine(coupon.FreeTrialUnit.ToString());
```

Support Free Trial Coupons

---

History.md
Library/Properties/AssemblyInfo.cs

* Allow null netterms https://github.com/recurly/recurly-client-net/pull/178
* Add SubscriptionState Failed https://github.com/recurly/recurly-client-net/pull/177
* Support free trial coupons https://github.com/recurly/recurly-client-net/pull/181

Bump 1.4.3

---

Library/Subscription.cs

Allow to skip trial period by setting date in past refer to https://dev.recurly.com/docs/preview-subscription

Allow to skip trial period by setting date in past

---

History.md
Library/List/UsageList.cs
Library/Recurly.csproj
Library/Usage.cs

Resolves #187 
```csharp
var subscriptionUuid = "37bfef7a8e44cfc3817b7a43eba8a6e6";
var subscriptionAddOnCode= "ip_addresses";
var usages = Usage.List(subscriptionUuid, subscriptionAddOnCode);
while (usages.HasAny())
{
foreach (var u in usages)
Console.WriteLine("Usage: " + u.Amount);
usages = usages.Next;
}
```

Add UsageList class

---

History.md
Library/Properties/AssemblyInfo.cs

* fixed; Allow skip trial period by setting date in the past https://github.com/recurly/recurly-client-net/pull/183
* added; Add .vscode to gitignore https://github.com/recurly/recurly-client-net/pull/185
* added; UsageList class https://github.com/recurly/recurly-client-net/pull/188

Bump 1.4.4

---

Library/BillingInfo.cs

Adding ability to create billing info for PayPal payers.

Update BillingInfo.cs (Adding PayPal)

---

History.md
Library/Properties/AssemblyInfo.cs

* Allow addresses to be null, and don't force-create one when fetching … #186
* Update BillingInfo.cs (Adding PayPal) #191 
* Add Invoice Create and Preview data #193 
* Make po_number always available to write on Subscription #194

Bump 1.4.5

---

Library/Client.cs
Library/Error.cs
Library/Errors.cs
Library/Exception.cs
Library/InvalidCredentialsException.cs
Library/List/SubscriptionAddOnList.cs
Library/NotFoundException.cs
Library/Recurly.csproj
Library/ServerException.cs
Library/TransactionError.cs
Library/ValidationException.cs

This is work in progress attempt at resolving #197 
I've changed the API of exception so you can get the validation errors as well as the transaction error. Here is an example:
```csharp
{
class Program
{
static void Main(string[] args)
{
try
{
var accountCode = Guid.NewGuid().ToString().Replace("-", "");
var account = new Account(accountCode);
info.FirstName = "Verana";
info.LastName = "Example";
info.CreditCardNumber = "4000-0000-0000-0309"; // gateway timeout
info.VerificationValue = "123";
info.ExpirationMonth = 11;
info.ExpirationYear = 2018;
info.City = "New Orleans";
info.State = "LA";
info.PostalCode = "70115";
account.BillingInfo = info; // need to force set
var plan = Plans.Get("gold1");
var sub = new …
```

Parse transaction_error

---

History.md
Library/Properties/AssemblyInfo.cs

* Fix null Datetime Xml reading for Adjustment StartDate and UpdatedAt #199 
* Parse transaction_error #200 
* Updated test project to use latest version of Xunit #202
* Add total_billing_cycles reader #203

Bump 1.4.6

---

History.md
Library/Plan.cs

Fix TotalBillingCycles nil value

---

History.md
Library/Properties/AssemblyInfo.cs

Hotfix: Fixes a bug in 1.4.6
* Fix TotalBillingCycles nil value #206

Bump 1.4.7

---

Library/Invoice.cs
Library/Transaction.cs
Test/BaseTest.cs
Test/List/InvoiceListTest.cs

Added support for new invoice and transactions states for ACH billing

---

History.md
Library/Properties/AssemblyInfo.cs

* Write amazon_billing_agreement_id #209
* Added support for new invoice and transactions states for ACH billing #212 [Issue: #211]

Bump 1.4.8

---

History.md
Library/Properties/AssemblyInfo.cs

* Add missing enum values #215

Bump 1.4.10

---

Library/Account.cs
Library/BillingInfo.cs
Library/Coupon.cs
Library/Invoice.cs
Library/Plan.cs
Library/Subscription.cs
Library/Transaction.cs
Test/ExtensionTest.cs

Modified overridden gethashcode to work on null references

---

History.md
Library/Properties/AssemblyInfo.cs

* Automated export feature #221
* Modified overridden gethashcode to work on null references #220

Bump 1.4.11

---

History.md
Library/Properties/AssemblyInfo.cs

* API 2.5 additions #224 
* Sorting and Filtering parameters #217 
* Refactored Invoice/PreviewPendingCharges to be able to specify notes #222

Bump 1.4.12

---

Library/Plan.cs

Fixed a probable NRE in Plans.List()

---

History.md
Library/Client.cs
Library/Properties/AssemblyInfo.cs

Addresses #238 and bumps to 1.5.1.

Fix readxmlListDelegate usage and Bump to 1.5.1

---

Library/Subscription.cs

update postpone timestring for 24-hour formatting

update postpone timestring for 24-hour formatting

---

History.md
Library/Properties/AssemblyInfo.cs

* Fix Subscription#Postpone datetime format bug #244

Bump 1.6.1

---

Library/Subscription.cs

This change is for the `api_version_2_8` branch. It adds the writeable `ImportedTrial` flag to `Subscription`

ImportedTrial flag on Subscription

---

README.md

I noticed the README was a little stale and didn't give a good overview of how to start with the library. I thought it could use an update.

Update the README with `Overview` section

---

Library/Account.cs
Library/GiftCard.cs

Addresses #249 
```csharp
// first we create the gift card
var delivery = new Delivery(Delivery.DeliveryMethod.Email);
delivery.GifterName = "Benjamin";
delivery.FirstName = "Sally";
delivery.LastName = "DuMonde";
delivery.PersonalMessage = "Happy birthday!";
delivery.EmailAddress = "sally@example.com";
// the first param can be an account code for the gifter (if it exists) or an Account object for a new account
var giftCard = new GiftCard("benjamin-du-monde", delivery, "test_gift_card", 1000, "USD");
giftCard.Create();
Console.WriteLine(giftCard);
Console.WriteLine(giftCard.RedemptionCode);
// Now let's create sally's account
var recipientAccount = new Account("sally-du-monde");
// you don't need to call create here if the account already exists
recipientAccount.Create();
// Now let's …
```

Adds giftcard redeem endpoint

---

Library/AddOn.cs
Library/Adjustment.cs
Library/Plan.cs
Library/Subscription.cs
Library/SubscriptionAddOn.cs

Fix revenue_schedule_type spelling

---

Library/BillingInfo.cs

Add missing 'DinersClub' credit card type

---

Library/List/UsageList.cs
Library/Usage.cs

- Query usage records filtering by billing_status and datetime_type
- Get usage record by usageId
- Change "String" by "string"

Usage records query improvements

---

Library/AddOn.cs
Library/Adjustment.cs
Library/Plan.cs
Library/Subscription.cs
Library/SubscriptionAddOn.cs

Handle empty revenue schedule type for adjustments

---

Library/Account.cs
Library/CouponRedemption.cs
Library/Invoice.cs

Add filter to InvoiceList, redemption updated_at

---

Library/InvoiceCollection.cs
Library/List/InvoiceList.cs

This xml parsing on InvoiceCollection was not being performed correctly.

Fix InvoiceCollection#credit_invoices parsing

---

Library/Account.cs
Library/Adjustment.cs
Library/Configuration/Settings.cs
Library/Purchase.cs
Library/Subscription.cs

API Version 2.11

---

History.md
Library/Properties/AssemblyInfo.cs

* API Version 2.11 #286
* Add missing RevenueScheduleType values #287 
* Fix InvoiceCollection#credit_invoices parsing #283

Bump 1.11.1

---

History.md
Library/Properties/AssemblyInfo.cs

*  fix typo in Subscription#pause #289

Bump 1.11.2

---

Library/Account.cs
Library/Adjustment.cs
Library/Invoice.cs

* Resolves #267 (make product_code writeable on Adjustment)
* Resolves #285 (add closed_at to Account)
* Adds missing InvoiceStates
* Adds ShippingAddress to Invoice
* Fixes some null exceptions in parser

Fixes some small issues

---

Library/Subscription.cs

Hi There,
This change is based on https://github.com/recurly/recurly-client-net/issues/296
Regards,
Paul Power

Issue#296 - Expose subs accountcode to avoid unnecessary api requests

---

Library/Subscription.cs

This changes `RemainingBillingCycles` to be publicly writeable and serializes it in the xml.

Make Subscription#RemainingBillingCycles writeable

---

Library/List/RefundList.cs
Library/OpenAmountRefund.cs

Use EnumTransportCase for RefundMethod

---

History.md
Library/Properties/AssemblyInfo.cs

* Fix Usages Id parsing bug #305 
* Transaction should parse embedded account #306 
* Make Subscription#RemainingBillingCycles writeable #307 
* Use EnumTransportCase for RefundMethod #309

Bump 1.12.1

---

Library/Plan.cs
Library/Subscription.cs

Subscription Terms

---

History.md
Library/Properties/AssemblyInfo.cs

Fixes a regression issue introduced in 1.12.1
* Issue parsing Account#billing_info #315

Bump 1.12.3

---

History.md
Library/Properties/AssemblyInfo.cs

* Allow more nulls in BillingInfo (prevents parsing errors) #319

Bump 1.12.4

---

Library/Purchase.cs

The Purchases serializer was not writing the po_number element.

Add PoNumber to Purchases Serializer

---

History.md
Library/Properties/AssemblyInfo.cs

- Upgrade mono to fix TLS issue #321 
- 2.13 Custom Fields Support #322 
- Add PoNumber to Purchases Serializer #324

Bump 1.12.5

---

Library/Address.cs
Library/Invoice.cs
Test/InvoiceTest.cs

Allow editing of an invoice from the client.

Add ability to update an invoice

---

Test/AccountTest.cs
Test/BillingInfoTest.cs
Test/InvoiceTest.cs
Test/List/InvoiceListTest.cs
Test/SubscriptionTest.cs

Fixes the failures of the integration tests

Fix integration tests so they all pass

---

.gitignore
dist/recurly.nuspec
scripts/clean
scripts/release

Adding 2 scripts:
1. `clean` for cleaning the build artifacts
2. `release` for building and releasing the library

Add clean and release scripts

---

Library/Adjustment.cs
Library/Invoice.cs
Library/List/RefundList.cs
Library/OpenAmountRefund.cs
Library/Refund.cs
Test/InvoiceTest.cs

This is not a breaking change but does deprecate the current methods for doing refunds on Invoices.
A few changes here:
1. Added the `Invoice.RefundOptions` class as a way to pass all the new options to refunds.
2. Deprecated signatures for `Invoice#Refund` and `Invoice#RefundAmount`. Added new methods with new signatures that accept an instance of `RefundOptions`.
3. Added a set-only property `Invoice#Prorate`. This allows the programmer to prorate a specific adjustment on refund instead of all of them.
4. Added `AllCredit` and `AllTransaction` values to `Invoice.RefundMethod` enum.
Scripts:
```csharp
using System;
using Recurly;
{
class RefundAmountInvoice
{
{
// Gets the first `paid` invoice on the site
var invoice = …
```

Changes to Invoice Refunds needed for credit memos

---

Library/Configuration/Settings.cs

Adds the .Net Framework version and some OS information to the user agent.
Framework version code adapted from https://stackoverflow.com/a/951915

Add Framework and OS to user agent

---

Library/Account.cs

This adds support for the Account Hierarchy feature. Tests are not included because it is not GA yet and even when it comes out it will be behind a feature flag. Manual tests have been executed with the examples below.
Create an account with a parent account:
```c#
// Assumes account "example-124" exists
var account = new Account("example-123");
account.ParentAccountCode = "example-124";
account.Create();
```
Update an account to add a parent account:
```c#
// Assumes accounts "example-123" and "example-124" exist
var account = Accounts.Get("example-123");
account.ParentAccountCode = "example-124";
account.Update();
```
Update an account to remove a parent account:
```c#
// Assumes accounts "example-123" exists and has a parent
var account = Accounts.Get("example-123"); …
```

Add support for Account Hierarchy

---

History.md
Library/Account.cs
Library/Configuration/Settings.cs
Library/Properties/AssemblyInfo.cs
dist/recurly.nuspec

1.15.3 (stable) / 2019-03-12
This release brings us up to API version 2.19. There are no breaking changes.
* Add support for Account Hierarchy [PR](https://github.com/recurly/recurly-client-net/pull/367)
* Fix issues with AddOns in Subscription Change [PR](https://github.com/recurly/recurly-client-net/pull/381)

Release version 1.15.3 / API version 2.19

---

Recurly/Client.cs

Adds CreateCouponRedemption and PauseSubscription as they were breaking the build before.

Subscription Pause and Create Coupon Redemption

---

Library/Delivery.cs

The `<personal_message>` tag wasn't being created or read in the XML for creating/getting a gift card.

Add PersonalMessage to XML read and write

---

History.md
Library/Properties/AssemblyInfo.cs
dist/recurly.nuspec

1.15.4 (stable) / 2019-03-19
* Fix XML for GiftCard Personal Message [PR](https://github.com/recurly/recurly-client-net/pull/386)

Bump to version 1.15.4

---

Recurly/Client.cs
Recurly/Resources/AccountAcquisitionCost.cs
Recurly/Resources/BillingInfoPaymentMethod.cs
Recurly/Resources/BillingInfoUpdatedBy.cs
Recurly/Resources/Coupon.cs
Recurly/Resources/CouponDiscountTrial.cs
Recurly/Resources/ExternalRefund.cs
Recurly/Resources/FraudInfo.cs
Recurly/Resources/InvoiceAddress.cs
Recurly/Resources/LineItem.cs
Recurly/Resources/Plan.cs
Recurly/Resources/PlanCreate.cs
Recurly/Resources/PlanHostedPages.cs
Recurly/Resources/PlanUpdate.cs
Recurly/Resources/SubscriptionCreate.cs
Recurly/Resources/SubscriptionUpdate.cs
Recurly/Resources/TransactionPaymentGateway.cs
Recurly/Resources/TransactionPaymentMethod.cs

Ran generator to update library

V3 Update v2018-08-09

---

README.md
Recurly.Tests/BaseClientTest.cs
Recurly.Tests/ClientTest.cs
Recurly.Tests/Errors/ApiErrorTest.cs
Recurly.Tests/Fixtures.cs
Recurly.Tests/JsonSerializerTest.cs
Recurly.Tests/PagerTest.cs
Recurly.Tests/UtilsTest.cs
Recurly/BaseClient.cs
Recurly/Client.cs
Recurly/JsonSerializer.cs
Recurly/Pager.cs

This has a couple changes in it:
1. Adds async operations to the client
2. Adds async method to pager
3. Refactors pagination to be like the other clients (calling List* now does not make an http. The call is now made when consuming the pager)
4. Re-organizes specs to get > 80% coverage (will be more to come on this)

Dotnet Async Operations

---

Library/Invoice.cs

Adds a `ForceCollect` method to `Invoice` for this endpoint: https://dev.recurly.com/docs/collect-an-invoice

Add ForceCollect

---

History.md
Library/Properties/AssemblyInfo.cs
dist/recurly.nuspec

1.15.5 (stable) / 2019-04-30
* Add ForceCollect to Invoice [PR](https://github.com/recurly/recurly-client-net/pull/393)

Bump to version 1.15.5

---

Library/List/ShippingMethodList.cs
Library/Purchase.cs
Library/Recurly.csproj
Library/ShippingFee.cs
Library/ShippingMethod.cs
Library/Subscription.cs

This adds support for shipping fees and the new shipping methods endpoint.
List shipping methods:
```C#
using System.Linq;
var shippingMethods = ShippingMethods.List(FilterCriteria.Instance.WithOrder(FilterCriteria.Order.Asc));
while (shippingMethods.Any())
{
foreach (var shippingMethod in shippingMethods)
Console.WriteLine("Shipping Method: " + shippingMethod.Code);
shippingMethods = shippingMethods.Next;
}
```
Get a shipping method:
```C#
var shippingMethod = ShippingMethods.Get("fast_fast_fast");
Console.WriteLine(shippingMethod.Name);
```
Purchase with shipping fees (note: either account must have shipping address, or purchase must have shipping_address_id):
```C#
using System.Collections.Generic;
// Assumes plan "gold" exists on the site
// Assumes shipping method 'fast_fast_fast' …
```

Add support for shipping fees

---

README.md
Recurly/Recurly.csproj

Merge after https://github.com/recurly/recurly-client-net/pull/408
* Implement code formatting https://github.com/recurly/recurly-client-net/commit/d98860725b5e14a437a626d06fd57f363efb77e4
* Enable pagination parameters https://github.com/recurly/recurly-client-net/commit/f8cd269b30820c327e6fc214ad8ea713332c6439
No breaking changes this release.

Bump to 3.0.0-beta.4

---

Library/Plan.cs

Consider a program like this:
```csharp
var plan = Plans.Get("gold");   // existing plan code 
plan.PlanCode = "newgold";   // plan code does not exist yet
plan.Update();
Console.WriteLine($"Plan code changed: {plan.PlanCode}");
```
The `plan.Update()` call will fail since the plan object uses the PlanCode to build the url to reference itself (and newgold) does not yet exist.
The ideal / global solution would be to have these object store their href that they get back from the server but that's too disruptive of a lift: https://github.com/recurly/recurly-client-net/issues/142
This is a compromise solution and fixes the problem locally to Plan. It caches the code in `_referencePlanCode` and only sets that cache when the object is being parsed from the xml. It then uses this cached code (if …

Allow programmer to change the PlanCode

---

Recurly/Errors/ApiErrors.cs
Recurly/Utils.cs
scripts/test

Need to make the Error parsing more liberal. Also looking adding the strict mode for testing.

Make Error parsing more robust and support STRICT_MODE

---

History.md
Library/BillingInfo.cs
Library/Configuration/Settings.cs
Library/Properties/AssemblyInfo.cs
Library/TransactionError.cs
Library/TransactionErrorEnum.cs
dist/recurly.nuspec

1.15.8 (stable) / 2019-06-27
* Support 3DS authentication [PR](https://github.com/recurly/recurly-client-net/pull/415)
* Accomodate null value in Bank Account Type [PR](https://github.com/recurly/recurly-client-net/pull/422)

Release version 1.15.8

---

README.md
Recurly/Recurly.csproj

* Latest 2018-08-09 changes (including purchases) https://github.com/recurly/recurly-client-net/pull/424
No Breaking Changes

3.0.0.beta.5

---

Recurly/Resources/AccountAcquisition.cs
Recurly/Resources/AccountAcquisitionUpdatable.cs
Recurly/Resources/BillingInfo.cs
Recurly/Resources/CouponDiscount.cs
Recurly/Resources/ErrorMayHaveTransaction.cs
Recurly/Resources/InvoiceRefund.cs
Recurly/Resources/LineItemCreate.cs
Recurly/Resources/Transaction.cs
Recurly/Resources/TransactionError.cs

* Latest v2018-08-09 Changes
* Includes fix for Dictionaries that should have been typed Resources

Latest v2018-08-09 Changes

---

README.md
Recurly/Recurly.csproj

* Latest v2018-08-09 Changes (Includes fix for Dictionaries that should have been typed Resources) #428

Bump 3.0.0-beta.6

---

Recurly.Tests/PagerTest.cs
Recurly/Pager.cs

In consulting with @aaron-suarez on the Java pager, I realized there wasn't a test for an empty page so I added it and it failed. This resulted me in moving some things around to better handle this case.
```csharp
int count = 0;
var accountId = Utils.CreateAccount(client).Id;
// Try with shipping addresses and without
//Utils.CreateShippingAddress(client, accountId);
var addresses = client.ListShippingAddresses(accountId);
foreach(ShippingAddress address in addresses)
{
count++;
}
Console.WriteLine("For-each count:");
// should be 0 (or 1 if CreateShippingAddress uncommented)
Console.WriteLine(count);
```
```csharp
int count = 0;
var accounts = client.ListAccounts(null, 200);
foreach(Account account in accounts)
{
count++;
}
Console.WriteLine("For-each count:");
Console.WriteLine(count); …
```

Fix Pager empty page bug

---

Library/GiftCard.cs
Library/Invoice.cs
Library/SubscriptionChange.cs

GiftCard#create
Invoice#force_collect
Subscription#update
All now optionally take billing infos

PSD2 billing info changes

---

.bumpversion.cfg
README.md
Recurly/Recurly.csproj
Recurly/Resources/CouponRedemption.cs
Recurly/Resources/CouponRedemptionMini.cs
Recurly/Resources/PaymentMethod.cs

A few more tweaks I noticed missing in the OpenAPI specs. `routing_number_bank` as pointed out in #445

Release 3.0.0-beta.7

---

History.md
Library/Properties/AssemblyInfo.cs
dist/recurly.nuspec

- Add shipping address to Purchase [PR] (https://github.com/recurly/recurly-client-net/pull/452)

Release 1.16.3

---

Recurly/BaseClient.cs
Recurly/Client.cs
Recurly/FileSerializer.cs
Recurly/Resources/BinaryFile.cs
Recurly/Resources/Item.cs
Recurly/Resources/ItemCreate.cs
Recurly/Resources/ItemUpdate.cs
Recurly/Resources/LineItem.cs
Recurly/Resources/LineItemCreate.cs
Recurly/Resources/Pricing.cs
openapi/api.yaml

- Adds capability to support `application/pdf` responses
- Adds `Item` support

Generated Updates for API version v2019-10-10

---

.bumpversion.cfg
Recurly/Recurly.csproj

* Adds PDF support https://github.com/recurly/recurly-client-net/pull/459
* Adds `Item` support https://github.com/recurly/recurly-client-net/pull/459
* Adds 3ds support https://github.com/recurly/recurly-client-net/pull/458/files

Release 3.1.0

---

Library/Account.cs
Library/Adjustment.cs
Library/Configuration/Settings.cs
Library/Item.cs
Library/List/ItemList.cs
Library/Recurly.csproj
Test/AdjustmentTest.cs
Test/BaseTest.cs
Test/Fixtures/adjustments/show-200.xml
Test/Fixtures/items/show-200.xml
Test/ItemTest.cs
Test/Recurly.Test.csproj

Add Item class to dotnet Client Library
To create an item:
```csharp
var item = new Item("pink_sweats", "Pink Sweats");
item.Create();
```
To list all items:
```csharp
var items = Items.List();
while (items.Any())
{
foreach (var item in items)
Console.WriteLine("Item: " + item.Name);
items = items.Next;
}
```
To look up an item (item_code required):
```csharp
var item = Items.Get("pink_sweats");
```
To update an item (item_code required):
```csharp
var item = Items.Get("pink_sweats");
item.Name = "Pink Sweatpants";
item.Update();
```
To delete an item (item_code required):
```csharp
var item = Items.Get("pink_sweats");
item.Deactivate();
```
To restore an item (item_code required):
```csharp
var item = Items.Get("pink_sweats");
item.Reactivate();
```

Add Item class

---

.bumpversion.cfg
Recurly/Recurly.csproj

* Properly Handle Transaction Errors  #465

Release 3.1.1

---

.bumpversion.cfg
Recurly/Recurly.csproj

*  Allow object attributes #468

Release 3.2.0

---

.bumpversion.cfg
Recurly/Recurly.csproj
Recurly/Resources/LineItemCreate.cs
Recurly/Resources/PurchaseCreate.cs
Recurly/Resources/ShippingAddress.cs
openapi/api.yaml

* Adds `origin` to `LineItemCreate`
* Adds `object` to `ShippingAddress`

Synchronize latest V3 Changes

---

Recurly/BaseClient.cs
Recurly/Constants.cs
Recurly/Pager.cs
Recurly/RecurlyStringEnumConverter.cs
scripts/clean

Laying groundwork for Enum support. Enums will be enabled in the next major version.

Initial addition of code to support enum types

---

Library/Adjustment.cs

- `xmlWriter.WriteElementString("item_code", ItemCode)` runs if ItemCode is not null.

Request will include item_code if ItemCode has a value.

---

Recurly/BaseClient.cs
Recurly/Client.cs
Recurly/FileSerializer.cs
Recurly/JsonSerializer.cs
Recurly/Pager.cs

Now that my editor is properly setup, I've realized many of these imports aren't being used.

Cleanup unused imports

---

Recurly/Errors/ApiErrors.cs
Recurly/Resources/Account.cs
Recurly/Resources/AccountAcquisition.cs
Recurly/Resources/AccountAcquisitionUpdatable.cs
Recurly/Resources/AccountBalance.cs
Recurly/Resources/AccountCreate.cs
Recurly/Resources/AccountPurchase.cs
Recurly/Resources/AccountUpdate.cs
Recurly/Resources/BillingInfoCreate.cs
Recurly/Resources/Coupon.cs
Recurly/Resources/CouponMini.cs
Recurly/Resources/CreditPayment.cs
Recurly/Resources/Invoice.cs
Recurly/Resources/Item.cs
Recurly/Resources/ItemCreate.cs
Recurly/Resources/ItemUpdate.cs
Recurly/Resources/LineItem.cs
Recurly/Resources/PaymentMethod.cs
Recurly/Resources/Subscription.cs
Recurly/Resources/SubscriptionAddOn.cs
Recurly/Resources/SubscriptionChange.cs
Recurly/Resources/SubscriptionChangeCreate.cs
Recurly/Resources/SubscriptionCreate.cs
Recurly/Resources/SubscriptionPurchase.cs
Recurly/Resources/SubscriptionUpdate.cs
Recurly/Resources/Transaction.cs
openapi/api.yaml

* More documentation
* `Account#has_*` flag attributes
* Include `RateLimitedError`
* Gateway Token Support

Latest v2019-10-10 Changes

---

History.md
Library/Properties/AssemblyInfo.cs
dist/recurly.nuspec

Release 1.17.1
- Add 'capture' and 'cancel' to Purchase [PR](https://github.com/recurly/recurly-client-net/pull/474)
- Repair broken tests [PR](https://github.com/recurly/recurly-client-net/pull/475)
- Add external_sku to Adjustment [PR](https://github.com/recurly/recurly-client-net/pull/476)
- Request will include item_code if ItemCode has a value [PR](https://github.com/recurly/recurly-client-net/pull/477)

Release 1.17.1

---

Recurly/Client.cs
Recurly/Resources/AddOn.cs
Recurly/Resources/AddOnCreate.cs
Recurly/Resources/AddOnUpdate.cs
Recurly/Resources/ItemMini.cs
Recurly/Resources/PaymentMethod.cs
openapi/api.yaml

* convert trial endpoint
* item-backed add-ons
* IBAN billing info

Latest generated changes for v2019-10-10

---

.bumpversion.cfg
Recurly/Recurly.csproj

* Latest generated changes for v2019-10-10 #484
* convert trial endpoint
* item-backed add-ons
* IBAN billing info
* Fix a DateTime Unit Tests when not in UTC #482
* Fixes a unit test that fails locally when not in UTC.
* Adds a float specification to the object added to the Dictionary.
* .gitignore updates to not checking build packages or Rider IDE files.
* Latest v2019-10-10 Changes #479
* More documentation
* `Account#has_*` flag attributes
* Include `RateLimitedError`
* Gateway Token Support
* Cleanup unused imports #478

Release 3.4.0

---

.bumpversion.cfg
Recurly/Recurly.csproj

[Full Changelog](https://github.com/recurly/recurly-client-dotnet/compare/3.4.0...HEAD)
- Adding changelog and updated release scripts [\#494](https://github.com/recurly/recurly-client-dotnet/pull/494) ([douglasmiller](https://github.com/douglasmiller))
- Fri Mar 20 17:39:58 UTC 2020 Upgrade API version v2019-10-10 [\#493](https://github.com/recurly/recurly-client-dotnet/pull/493) ([douglasmiller](https://github.com/douglasmiller))
- Add request for stack trace in issue report [\#487](https://github.com/recurly/recurly-client-dotnet/pull/487) ([bhelx](https://github.com/bhelx))

Release 3.4.1

---

Library/AddOn.cs
Library/Configuration/Settings.cs
Library/Recurly.csproj
Library/Tier.cs
Test/AddOnTest.cs
Test/Recurly.Test.csproj

To create add-on with tiers:
```c#
var addon = plan.NewAddOn("plant", "Plant");
addon.TierType = "tiered";
var tier1 = new Tier();
tier1.UnitAmountInCents.Add("USD", 100);
tier1.EndingQuantity = 60;
addon.Tiers.Add(tier1);
var tier2 = new Tier();
tier2.UnitAmountInCents.Add("USD", 50);
addon.Tiers.Add(tier2);
addon.Create();
```

Tiered Pricing

---

Library/AddOn.cs
Library/BillingInfo.cs
Library/Configuration/Settings.cs
Library/List/SubscriptionAddOnList.cs
Library/Recurly.csproj
Library/SubscriptionAddOn.cs
Library/Tier.cs
Test/AddOnTest.cs
Test/BillingInfoTest.cs
Test/Recurly.Test.csproj

- Tiered Pricing: Enable Add Ons to support 3 new pricing models (Tiered, Volume, and Stairstep)
- Add IBAN bank info as a part of billing info
- Add Mandate ID as part of billing info

Merge v2.26 features into v2 branch for release

---

Recurly/Resources/AddOn.cs
Recurly/Resources/AddOnCreate.cs
Recurly/Resources/AddOnUpdate.cs
Recurly/Resources/SubscriptionAddOn.cs
Recurly/Resources/SubscriptionAddOnCreate.cs
Recurly/Resources/SubscriptionAddOnTier.cs
Recurly/Resources/SubscriptionAddOnUpdate.cs
Recurly/Resources/Tier.cs
openapi/api.yaml

* Add `optional` to AddOnUpdate
* Adding quantity based pricing support

Tue Apr 14 20:22:18 UTC 2020 Upgrade API version v2019-10-10

---

Recurly.Tests/BaseClientTest.cs
Recurly/BaseClient.cs

Encode forward slashes in URL parameters

---

.bumpversion.cfg
Recurly/Recurly.csproj

[Full Changelog](https://github.com/recurly/recurly-client-dotnet/compare/3.5.1...HEAD)
- Latest Features [\#518](https://github.com/recurly/recurly-client-dotnet/pull/518) ([bhelx](https://github.com/bhelx))
- Setting Next in Pager.Build to fix async pager requests [\#519](https://github.com/recurly/recurly-client-dotnet/pull/519) ([douglasmiller](https://github.com/douglasmiller))

Release 3.6.0

---

.bumpversion.cfg
Recurly/Recurly.csproj

[Full Changelog](https://github.com/recurly/recurly-client-dotnet/compare/3.6.0...HEAD)
- Updating internal scripts to use globally installed dotnet-format [\#517](https://github.com/recurly/recurly-client-dotnet/pull/517) ([douglasmiller](https://github.com/douglasmiller))
- Applying query params to url before creating the request [\#521](https://github.com/recurly/recurly-client-dotnet/pull/521) ([douglasmiller](https://github.com/douglasmiller))
- Adding MockClient and refactoring tests to use it [\#522](https://github.com/recurly/recurly-client-dotnet/pull/522) ([douglasmiller](https://github.com/douglasmiller))

Release 3.6.1

---

README.md

Temporary placeholder for those wanting to get a quick webhooks integration going.

Document a way to handle webhooks

---

Test/BillingInfoTest.cs

Addresses https://github.com/recurly/recurly-client-dotnet/pull/490#discussion_r393273123

Repair test to expect a validation exception

---

.bumpversion.cfg
Recurly/Recurly.csproj

[Full Changelog](https://github.com/recurly/recurly-client-dotnet/compare/3.6.1...HEAD)
- ListAccountSubscriptions returning expired subscriptions when specifying state="live" [\#531](https://github.com/recurly/recurly-client-dotnet/issues/531)
- Fixing query parameter handling in the Pager class [\#532](https://github.com/recurly/recurly-client-dotnet/pull/532) ([douglasmiller](https://github.com/douglasmiller))
- Document a way to handle webhooks [\#526](https://github.com/recurly/recurly-client-dotnet/pull/526) ([bhelx](https://github.com/bhelx))
- Adding RequestOptions to facilitate passing custom request headers [\#524](https://github.com/recurly/recurly-client-dotnet/pull/524) ([douglasmiller](https://github.com/douglasmiller))

Release 3.7.0

---

.bumpversion.cfg
Recurly/Recurly.csproj

[Full Changelog](https://github.com/recurly/recurly-client-dotnet/compare/3.7.0...HEAD)
- Removing overloaded Async operation methods [\#537](https://github.com/recurly/recurly-client-dotnet/pull/537) ([douglasmiller](https://github.com/douglasmiller))

Release 3.7.1

---

Library/BillingInfo.cs
Library/Configuration/Settings.cs
Test/BillingInfoTest.cs

Added `sort_code` and `type` fields to support BACS payment type.

BACS support

---

.bumpversion.cfg
Recurly/Recurly.csproj

[Full Changelog](https://github.com/recurly/recurly-client-dotnet/compare/3.7.1...HEAD)
- Mon Jun 29 17:10:49 UTC 2020 Upgrade API version v2019-10-10 [\#541](https://github.com/recurly/recurly-client-dotnet/pull/541) ([douglasmiller](https://github.com/douglasmiller))

Release 3.8.0

---

Recurly/Client.cs
Recurly/Resources/SubscriptionAddOn.cs
Recurly/Resources/SubscriptionAddOnCreate.cs
Recurly/Resources/SubscriptionChangePreview.cs
openapi/api.yaml

- Adds `preview_subscription_change` operation.
- Adds `add_on_source` property to `SubscriptionAddOnCreate` and `SubscriptionAddOn`.

Wed Jul  1 02:07:15 UTC 2020 Upgrade API version v2019-10-10

---

.bumpversion.cfg
Recurly/Recurly.csproj

[Full Changelog](https://github.com/recurly/recurly-client-dotnet/compare/3.8.0...HEAD)
- Wed Jul  1 02:07:15 UTC 2020 Upgrade API version v2019-10-10 [\#545](https://github.com/recurly/recurly-client-dotnet/pull/545) ([douglasmiller](https://github.com/douglasmiller))

Release 3.9.0

---

Recurly/Resources/SubscriptionAddOnCreate.cs
Recurly/Resources/SubscriptionAddOnUpdate.cs
openapi/api.yaml

- Adds `AddOnSource` to `SubscriptionAddOnUpdate`

Mon Jul  6 14:48:58 UTC 2020 Upgrade API version v2019-10-10

---

.bumpversion.cfg
Recurly/Recurly.csproj

[Full Changelog](https://github.com/recurly/recurly-client-dotnet/compare/3.9.0...HEAD)
- Mon Jul  6 14:48:58 UTC 2020 Upgrade API version v2019-10-10 [\#547](https://github.com/recurly/recurly-client-dotnet/pull/547) ([douglasmiller](https://github.com/douglasmiller))

Release 3.10.0

---

Library/BillingInfo.cs
Test/BillingInfoTest.cs

Reverts recurly/recurly-client-dotnet#550
Will be added back later as part of an API v2.28 change

Revert "BECS support"

---

Recurly/IClient.cs

Regenerates the IClient with the changes made for empty responses

Regenerate interface with EmptyResource changes

---

Recurly/Client.cs
Recurly/IClient.cs
Recurly/Resources/AddOn.cs
Recurly/Resources/AddOnCreate.cs
Recurly/Resources/AddOnMini.cs
Recurly/Resources/AddOnUpdate.cs
Recurly/Resources/MeasuredUnit.cs
Recurly/Resources/MeasuredUnitCreate.cs
Recurly/Resources/MeasuredUnitUpdate.cs
Recurly/Resources/SubscriptionAddOn.cs
Recurly/Resources/SubscriptionAddOnCreate.cs
Recurly/Resources/SubscriptionAddOnUpdate.cs
Recurly/Resources/SubscriptionChange.cs
Recurly/Resources/SubscriptionChangePreview.cs
Recurly/Resources/SubscriptionPurchase.cs
Recurly/Resources/Usage.cs
Recurly/Resources/UsageCreate.cs
openapi/api.yaml

* Usage and measured units support
* Added `InvoiceCollection` to response for `CreateSubscriptionChange`
* Support `AddOnType` on addons

 Latest Changes for 2019-10-10 (usage, measured units, etc)

---

.bumpversion.cfg
Recurly/Recurly.csproj

[Full Changelog](https://github.com/recurly/recurly-client-dotnet/compare/3.10.0...HEAD)
-  Latest Changes for 2019-10-10 \(usage, measured units, etc\) [\#557](https://github.com/recurly/recurly-client-dotnet/pull/557) ([bhelx](https://github.com/bhelx))
- Adds IClient interface and makes Client implement it [\#554](https://github.com/recurly/recurly-client-dotnet/pull/554) ([bhelx](https://github.com/bhelx))
- Adding Response class to Resource [\#549](https://github.com/recurly/recurly-client-dotnet/pull/549) ([douglasmiller](https://github.com/douglasmiller))
- Namespaces Response and Header [\#556](https://github.com/recurly/recurly-client-dotnet/pull/556) ([bhelx](https://github.com/bhelx))
- Regenerate interface with …

Release 3.11.0

---

Recurly.Tests/BaseClientTest.cs
Recurly/BaseClient.cs
Recurly/Errors/ApiErrors.cs
Recurly/Http.cs
Recurly/IEventHandler.cs
scripts/format

Addresses #534 
Client EventHandlers are a generic interface for "hooking" into the http request / response events (and potentially other events the client might emit in the future). We'll be leaving it undocumented for the time being until we can get some more feedback. I've also left out async support for the time being. The generic handler interface can be used to do simple logging, or do something more interactive like a rate limit throttling.
EventHandler interface:
```csharp
namespace Recurly
{
public interface IEventHandler
{
void OnRequest(Recurly.Http.Request request);
void OnResponse(Recurly.Http.Response response);
}
}
```
Here is an example of a ratelimiter adapted from #534
```csharp
class RateLimiter : Recurly.IEventHandler
{
private int? sleepTime;
public RateLimiter() { …
```

Client Event Handlers

---

Recurly/Resources/CouponCreate.cs
Recurly/Resources/SubscriptionChange.cs
Recurly/Resources/SubscriptionChangeCreate.cs
Recurly/Resources/SubscriptionChangePreview.cs
openapi/api.yaml

- Adds Custom Fields to the Subscription Change and Subscription Change Preview endpoints.

Mon Aug 31 19:45:47 UTC 2020 Upgrade API version v2019-10-10

---

.bumpversion.cfg
Recurly/Recurly.csproj

[Full Changelog](https://github.com/recurly/recurly-client-dotnet/compare/3.11.0...HEAD)
- Mon Aug 31 19:45:47 UTC 2020 Upgrade API version v2019-10-10 [\#573](https://github.com/recurly/recurly-client-dotnet/pull/573) ([douglasmiller](https://github.com/douglasmiller))
- Fri Aug 21 16:21:53 UTC 2020 Upgrade API version v2019-10-10 [\#568](https://github.com/recurly/recurly-client-dotnet/pull/568) ([douglasmiller](https://github.com/douglasmiller))
- Code of Conduct [\#572](https://github.com/recurly/recurly-client-dotnet/pull/572) ([bhelx](https://github.com/bhelx))
- Client Event Handlers [\#560](https://github.com/recurly/recurly-client-dotnet/pull/560) ([bhelx](https://github.com/bhelx))

Release 3.12.0

---

Recurly/Client.cs
Recurly/Errors/ApiErrors.cs
Recurly/Errors/Factory.cs
Recurly/IClient.cs
Recurly/Resources/Coupon.cs
Recurly/Resources/ExportDates.cs
Recurly/Resources/ExportFile.cs
Recurly/Resources/ExportFiles.cs
Recurly/Resources/UniqueCouponCode.cs
Recurly/Resources/Usage.cs
openapi/api.yaml

* Adds `GetExportDates`, `GetExportDatesAsync`, `GetExportFiles` and `GetExportFilesAsync` operations for the [Automated Exports](https://developers.recurly.com/api/v2019-10-10/index.html#tag/automated_exports) feature.
* Adds `ExportDates`, `ExportFiles`, and `ExportFile` resources to support the `Automated Exports` feature.
* Adds `BulkCouponCode` and `BulkCouponId` attributes to the `UniqueCouponCode` and `Coupon` resources.
* Adds `UnitAmount` and `UsagePercentage` attributes to the `Usage` resource.
Non-breaking update to error classes to give them a hierarchical structure. This will facilitate differentiating between a `Errors.Client` and a `Errors.Server` for example.
New error classes have also been added to be parent classes for some existing errors (e.g. `Errors.Forbidden` is a …

Latest Changes for 2019-10-10 (Automated Exports, hierarchical errors, additional resource data attributes)

---

Recurly/Resources/AddOnCreate.cs
Recurly/Resources/Coupon.cs
Recurly/Resources/ExportDates.cs
Recurly/Resources/ExportFiles.cs
Recurly/Resources/LineItemCreate.cs
Recurly/Resources/SubscriptionAddOnCreate.cs
openapi/api.yaml

* Fixes issues with Automated Exports endpoints.

Latest Changes for 2019-10-10

---

.bumpversion.cfg
Recurly/Recurly.csproj

[Full Changelog](https://github.com/recurly/recurly-client-dotnet/compare/3.12.0...HEAD)
- Latest Changes for 2019-10-10 [\#579](https://github.com/recurly/recurly-client-dotnet/pull/579) ([douglasmiller](https://github.com/douglasmiller))
- Latest Changes for 2019-10-10 \(Automated Exports, hierarchical errors, additional resource data attributes\) [\#576](https://github.com/recurly/recurly-client-dotnet/pull/576) ([douglasmiller](https://github.com/douglasmiller))
- Adding hierarchical errors and moving the error factory [\#569](https://github.com/recurly/recurly-client-dotnet/pull/569) ([douglasmiller](https://github.com/douglasmiller))

Release 3.13.0

---

Recurly/Client.cs
Recurly/IClient.cs
openapi/api.yaml

* Adds `RestoreCoupon` and `RestoreCouponAsync` operations.

Mon Oct 19 20:38:52 UTC 2020 Upgrade API version v2019-10-10

---

.bumpversion.cfg
Recurly/Recurly.csproj

[Full Changelog](https://github.com/recurly/recurly-client-dotnet/compare/3.13.1...HEAD)
- Mon Oct 19 20:38:52 UTC 2020 Upgrade API version v2019-10-10 [\#585](https://github.com/recurly/recurly-client-dotnet/pull/585) ([douglasmiller](https://github.com/douglasmiller))

Release 3.14.0

---

.bumpversion.cfg
Recurly/Recurly.csproj

[Full Changelog](https://github.com/recurly/recurly-client-dotnet/compare/3.14.0...HEAD)
- Latest Changes for 2019-10-10 \(Wallet, Item Coupons\) [\#589](https://github.com/recurly/recurly-client-dotnet/pull/589) ([douglasmiller](https://github.com/douglasmiller))
- Add test coverage for unknown error types [\#587](https://github.com/recurly/recurly-client-dotnet/pull/587) ([jguidry-recurly](https://github.com/jguidry-recurly))

Release 3.15.0

---

Test/BillingInfoTest.cs

Amends test to reflect valid request and exception thrown.

Fix test: create billing info (IBAN)

---

README.md

Revised readme to call out Header case sensitivity

Update readme to include memo on headers

---

.bumpversion.cfg
Recurly/Recurly.csproj

[Full Changelog](https://github.com/recurly/recurly-client-dotnet/compare/3.15.0...HEAD)
- Latest Changes for 2019-10-10 \(tax\_identifier / tax\_identifier\_type\) [\#597](https://github.com/recurly/recurly-client-dotnet/pull/597) ([douglasmiller](https://github.com/douglasmiller))
- Latest Changes for 2019-10-10 [\#594](https://github.com/recurly/recurly-client-dotnet/pull/594) ([douglasmiller](https://github.com/douglasmiller))
- Update readme to include memo on headers [\#595](https://github.com/recurly/recurly-client-dotnet/pull/595) ([joannasese](https://github.com/joannasese))

Release 3.16.0

---

.bumpversion.cfg
Recurly/Recurly.csproj

[Full Changelog](https://github.com/recurly/recurly-client-dotnet/compare/3.16.0...HEAD)
- Latest Changes for 2019-10-10 [\#599](https://github.com/recurly/recurly-client-dotnet/pull/599) ([douglasmiller](https://github.com/douglasmiller))

Release 3.17.0

---

.bumpversion.cfg
Recurly/Recurly.csproj

[Full Changelog](https://github.com/recurly/recurly-client-dotnet/compare/3.17.0...HEAD)
- Latest Changes for 2019-10-10 [\#606](https://github.com/recurly/recurly-client-dotnet/pull/606) ([douglasmiller](https://github.com/douglasmiller))

Release 3.18.0

---

README.md
Recurly.Tests/BaseClientTest.cs
Recurly.Tests/PagerTest.cs
Recurly/BaseClient.cs
Recurly/Http.cs
Recurly/Pager.cs

Some updates added to the 3.x client were missed when creating the 4.x client.

Sync updates not ported from 3.x client

---

Recurly/Resources/AddOnCreate.cs
Recurly/Resources/AddOnUpdate.cs
Recurly/Resources/Tier.cs
openapi/api.yaml

Adds `UsagePercentage` to the `Tier` resource.

Generated Latest Changes for v2021-02-25 (Usage Percentage on Tiers)

---

Recurly/Resources/BillingInfo.cs
Recurly/Resources/BillingInfoCreate.cs
Recurly/Resources/SubscriptionPurchase.cs
Recurly/Resources/Transaction.cs
openapi/api.yaml

- Adds `BackupPaymentMethod` property to the `BillingInfo` and `BillingInfoCreate` resources.
- Adds `BackupPaymentMethodUsed` property to the `Transaction` resource.

Generated Latest Changes for v2021-02-25 (Backup Payment Method)

---

Library/Account.cs
Library/AddOn.cs
Library/BillingInfo.cs
Library/Invoice.cs
Library/List/BillingInfoList.cs
Library/Purchase.cs
Library/Recurly.csproj
Library/Subscription.cs
Library/SubscriptionChange.cs
Test/AccountTest.cs
Test/BaseTest.cs
Test/BillingInfoTest.cs
Test/SubscriptionTest.cs

POST v2/accounts/:account_code/billing_infos
```c#
var account = Accounts.Get("code");
var binfo1 = new BillingInfo();
binfo1.FirstName = "Pineapple";
binfo1.LastName = "Berete";
binfo1.Address1 = "123 Main St";
binfo1.City = "New Orleans";
binfo1.State = "LA";
binfo1.Country = "US";
binfo1.PostalCode = "70212";
binfo1.CreditCardNumber = "4111111111111111";
binfo1.ExpirationMonth = 02;
binfo1.ExpirationYear = 2022;
binfo1.PrimaryPaymentMethod = true;
binfo1.BackupPaymentMethod = false;
account.CreateBillingInfo(binfo1);
```
GET v2/accounts/{account_code}/billing_infos
```c#
account.GetBillingInfos();
```
GET v2/accounts/{account_code}/billing_infos/{uuid}
```C#
account.GetBillingInfo("billingInfoUuid");
```
PUT v2/accounts/{account_code}/billing_infos/{billing_info_id}
```c#
var …
```

Wallet and Backup Payment
