- History.md
- Library/Account.cs
- Test/AccountTest.cs
This field will show up when the account is elligible and has been
location verified according to the VAT rules. It will be true when
passed and false when failed.
> Adding vat_location_valid field to Account

- History.md
- Library/Invoice.cs
- Library/OpenAmountRefund.cs
- Library/Recurly.csproj
- Test/InvoiceTest.cs
Allows an open amount refund and returns a new refund invoice.
Approvers: @cbarton
```csharp
var inv = Invoices.Get(1016);
Console.WriteLine(inv.InvoiceNumber);
// refund open amount for 50 cents
var refundInvoice = inv.RefundAmount(50);
Console.WriteLine(refundInvoice.InvoiceNumber);   // should be a new number [this is a new invoice]
Console.WriteLine(refundInvoice.SubtotalInCents);  // should be -50
```
> Support open amount refund

- History.md
- Library/Account.cs
The parse blows up when parsing a `VatLocationValid` field of type `nil`. This will avoid trying to parse in such a case and allow that tri-state field to exist.
cc/ @bhelx 
tests:
- with VAT location validation turned on and an account that is not in the EU
- The following should not blow up and return `False`: 
```
var account = Accounts.get('<account_code>');
Console.WriteLine(account.VatLocationValid);
```
- with an account in the EU (that has been validated)
- the above snippet should reflect the validation of that account.
> Do not parse nil as a boolean for the accounts vat location valid

- History.md
- Library/Invoice.cs
- Library/Subscription.cs
- Test/SubscriptionTest.cs
Trying to catch .NET up to the other libraries with notes support.
You can run this and verify the notes have changed. If you run again you should be able to see they have persisted.
```csharp
var sub = Subscriptions.Get("2bf76b61f7874bb58c384d45759be62c");
Console.WriteLine(sub.CustomerNotes);
Console.WriteLine(sub.TermsAndConditions);
Console.WriteLine(sub.VatReverseChargeNotes);
Dictionary<string, string> notes = new Dictionary<string, string>();
notes.Add("CustomerNotes", "New Customer Notes");
notes.Add("TermsAndConditions", "New T and C");
notes.Add("VatReverseChargeNotes", "New VAT Notes");
sub.UpdateNotes(notes);
Console.WriteLine(sub.CustomerNotes);
Console.WriteLine(sub.TermsAndConditions);
Console.WriteLine(sub.VatReverseChargeNotes);
```
> Adding notes support for Invoice and Subscription

- History.md
- Library/BillingInfo.cs
Adds ACH support for Billing Infos
cc/ @bhelx 
tests:
```c#
var account = Accounts.Get("<account-code>");
var info = account.BillingInfo;
info.NameOnAccount = "John Doe";
info.RoutingNumber = "125200057";
info.AccountNumber = "0123456789";
info.AccountType = BillingInfo.BankAccountType.Checking;
info.Address1 = "123 Fake St";
info.City = "San Francisco";
info.State = "CA";
info.PostalCode = "94107";
info.Create();
```
- check the billing info to see that it reflects that info
> Bank accounts (ACH feature)

- History.md
- Library/Invoice.cs
- Library/Transaction.cs
With VAT 2015 rules, all VAT taxed invoices need to be prefixed with the billing countries code, ie: `GB1000` for a customer in Great Britain.
This is already supported in the API and thusly needs to be supported in this client library.
In order to maintain backwards compatibility, I have separated the `InvoiceNumber` and `InvoiceNumberPrefix` fields for all objects that deal with invoices (`Transaction`, `Invoice`, `OriginalInvoice`). In order to make full use of this feature, all integrators should update their integration to use the `invoice.InvoiceNumberWithPrefix()` method instead of `invoice.InvoiceNumber`. 
This also adds convenience methods to get a `Transaction`'s invoice: `transaction.GetInvoice()` and the `Invoice`'s original invoice: `invoice.GetOriginalInvoice()`
cc/ @bhelx …
> Adds Invoice#InvoiceNumberPrefix and Invoice#InvoiceNumberWithPrefix

- History.md
- Library/Adjustment.cs
The tax information has been brought down to from the Invoice level to the Adjustment level. This unlocks those fields.
cc/ @snodgrass23 
tests:
```c#
var invoice = Invoices.Get("<invoice_with_tax_number>");
foreach (var adjustment in invoice.Adjustments)
{
Console.WriteLine("Adjustment: " + adjustment.Uuid + 
", Rate: " + adjustment.TaxRate + 
", Region: " + adjustment.TaxRegion +
", Type: " + adjustment.TaxType);
}
```
- should print out the tax info for the adjustments on that invoice
> Add 'TaxType', 'TaxRegion', 'TaxRate' to Adjustments

- History.md
- Library/Subscription.cs
For back dating bank account authorization when importing subscriptions, the API user can specify a `BankAccountAuthorizedAt` timestamp of when that authorization occurred.
cc/ @bhelx   
tests:
```csharp
var account = Accounts.Get("<account_code>");
var plan = Plans.Get("<plan_code>");
var sub = new Subscription(account, plan, "USD");
sub.BankAccountAuthorizedAt = DateTime.Parse("2015-02-05");
sub.Create();
sub = Subscriptions.Get(sub.Uuid);
Console.WriteLine(sub.BankAccountAuthorizedAt); //> 2/5/205 12:00:00AM
```
> Add BankAccountAuthorizedAt to Subscriptions

- History.md
- Library/Transaction.cs
- Test/Fixtures/transactions/create-422.xml
- Test/Fixtures/transactions/refund-202.xml
- Test/Fixtures/transactions/show-200-error.xml
- Test/Fixtures/transactions/show-200.xml
Adding `ip_address` to transactions now that it's exposed
https://docs.recurly.com/api/transactions#create-transaction
cc: @austinheap 
`var transaction = Transaction.Get(“<uuid>”)`;
`Console.WriteLine(transaction.IpAddress);`
> Adding ip_address to Transaction

- History.md
- Library/Invoice.cs
fixes https://github.com/recurly/recurly-client-net/issues/50
cc/ @bhelx 
test:
```c#
var invoice = Invoices.Get(<invoiceNumber>);
Console.WriteLine(invoice.TaxRegion);
```
> Add TaxRegion to Invoice

- History.md
- Library/Client.cs
fixes: https://github.com/recurly/recurly-client-net/issues/51
When a transaction is less than 3 cents, Recurly does not create a transaction since no money is transferred. Since there is no transaction, we return a 204, no content back, which breaks this SDK.
cc/ @bhelx 
test:
```
var account = Accounts.Get("pete");
var transaction = new Transaction(account, 0, "USD");
transaction.Create();
Console.WriteLine(transaction.AmountInCents); // Should be 0
```
> Do not attempt to parse an empty body response

- Library/Subscription.cs
- Test/SubscriptionTest.cs
This feature can be used like this...
Plan plan = Plans.Get("basic");
Account account = Accounts.Get("439683");
for (int i = 1; i < 4; i++)
{
var sub = new Subscription(account, plan, "USD");
sub.Bulk = true;
sub.Create();
}
> adds bulk parameter to sub. create method

- History.md
- Library/Invoice.cs
- Library/List/RefundList.cs
- Library/OpenAmountRefund.cs
cc/ @bhelx 
tests:
- Create a new invoice and make sure it is paid
- Attempt a transaction first line item refund:
```c#
var invoice = Invoices.Get("<invoice_number>");
var refInvoice =  invoice.Refund(invoice.Adjustments[0], refundPriority: Invoice.RefundOrderPriority.Transaction);
Console.WriteLine(refInvoice.InvoiceNumber);
```
- Create another invoice and make sure it is paid
- Attempt a transaction first open amount refund:
```c#
var invoice = Invoices.Get("<invoice_number>");
var refInvoice = invoice.RefundAmount(15, Invoice.RefundOrderPriority.Transaction);
Console.WriteLine(refInvoice.InvoiceNumber);
```
> add ability to specify the refund_apply_order in the API

- Library/Transaction.cs
- Test/TransactionTest.cs
Adds the ability to give a transaction a 'description' when creating one via the API. This 'description' will then appear on the invoice that is generated.
```csharp
var account = Accounts.Get("9637891");
var transaction = new Transaction(account, 5000, "USD");
transaction.Description = "Hey! Description";
transaction.Create();
var fromService = Transactions.Get(transaction.Uuid);
var invoice = fromService.GetInvoice();
var line_items = invoice.Adjustments;
Console.WriteLine("{0} ", line_items[0].Description);
```
> adds Description parameter to Transaction constructor

- History.md
- Library/Subscription.cs
This adds a `bulk` param for a Subscription postponement, which will allow for bypassing the 60 second wait.
Approvers: @cbarton
> Adding bulk parameter to Subscription

- Library/Adjustment.cs
- Library/Subscription.cs
- Test/InvoiceTest.cs
- Test/List/TransactionListTest.cs
- Test/Recurly.Test.csproj
- Test/SubscriptionTest.cs
- Test/TransactionTest.cs
Addresses: https://github.com/recurly/recurly-client-net/issues/95
Subscription xml reader wasn't expecting invoice xml that was coming back from the api when previewing a subscription. 
I also skipped deprecated unit tests.
Assure that this code does not throw an exception now. Insert values from your sandbox where applicable:
```csharp
var account = Accounts.Get("1");
var plan = Plans.Get("gold");
var subscription = new Subscription(account, plan, "USD");
subscription.Preview();          
```
> Fixed subscription preview

- History.md
- Library/Plan.cs
- README.md
- Test/PlanTest.cs
Exposing a `setup_fee_accounting` code to the client library since it's now available.
Also, added another link in the Readme to our docs site where folks can find examples of how to make calls with this lib and updated spacing.
> Adding setup_fee_accounting_code

- Library/AddOn.cs
- Library/Plan.cs
- Test/CouponRedemptionTest.cs
- Test/PlanTest.cs
Primarily fixes #75 
Also fixed the following unit tests:
- Create plan passed invalid characters to `SetupFeeAccountingCode`
- The Plan WriteXML also incorrectly used the value for `AccountingCode` (instead of `SetupFeeAccountingCode`) when writing `setup_fee_accounting_code`
- GetActiveRedemption returns null instead of throwing an exception so I check for null instead
> Fix AddOn.GetHashCode() exception

- History.md
- Library/Invoice.cs
Adding support for multiple redemptions endpoint on `Invoice`. `GetRedemption` should still work by taking the first redemption in the list.
Approvers: @csmb 
```csharp
// Also try invoices without any redemptions
var invoice = Invoices.Get(1379);
// Should be same redemption
Console.WriteLine(invoice.GetRedemption());
Console.WriteLine(invoice.GetRedemptions()[0]);
```
> Multiple Redemption support for Invoice

- History.md
- Library/Coupon.cs
Looks like the description readers were missing: https://github.com/recurly/recurly-client-net/issues/48
> Adding missing description readers to Coupon

- Library/Adjustment.cs
- Library/Subscription.cs
Supporting preview change. Finishing up this abandoned PR: https://github.com/recurly/recurly-client-net/pull/72
Example use:
```csharp
var sub = Subscriptions.Get("31f0e253f90804f5a0db4b4a82a0ff62");
sub.UnitAmountInCents = 5000;
// PreviewChange returns a new Subscription object
var subPreview = sub.PreviewChange();
Console.WriteLine(subPreview.UnitAmountInCents);
```
> Support Subscription Preview Change

- Library/Coupon.cs
Coupons should default to Type SingleCode unless specified otherwise. This fixes the tests as well.
> Coupons should default to SingleCode

- .travis.yml
- Test/AccountTest.cs
- Test/AdjustmentTest.cs
- Test/BillingInfoTest.cs
- Test/CouponRedemptionTest.cs
- Test/CouponTest.cs
- Test/FixtureImporterTests.cs
- Test/InvoiceTest.cs
- Test/List/AccountListTest.cs
- Test/List/InvoiceListTest.cs
- Test/List/PlanListTest.cs
- Test/List/SubscriptionListTest.cs
- Test/List/TransactionListTest.cs
- Test/PlanTest.cs
- Test/Recurly.Test.csproj
- Test/RecurlyFact.cs
- Test/SubscriptionTest.cs
- Test/SystemTest.cs
- Test/TestEnvironment.cs
- Test/TransactionTest.cs
Goal is to get Travis CI working as described here: https://github.com/recurly/recurly-client-net/issues/110
My idea is to replace all FactAttributes with our own `RecurlyFact` in which `scenarios` can be added. When run in travis, the tests will skip all the `Integration` scenarios.
This skips a lot of tests but at least gets something running. We can start enforcing unit tests after this.
Also, I can run the integration tests locally before releases and before merging a PR.
> Add Travis file and skip failing test

- History.md
- Library/Subscription.cs
**Description**: Now, calling `subscription.Invoice` will return the invoices associated with that subscription. Finishes https://github.com/recurly/recurly-client-net/pull/115
**Testing**: See an invoice returned for a subscription. 
```
var sub = Subscriptions.Get("35d0c3353c31fa244837c3402197a26f");
var inv = sub.Invoice;
Console.ReadLine();
```
> Referencing an `Invoice` from a `Subscription` returns the invoice

- History.md
- Library/Subscription.cs
- Test/SubscriptionTest.cs
PreviewSubscription() integration test was failing due to not knowing about the Open state as well as thinking the subscription would be active.
> Fix integration test and add open state

- History.md
- Library/Properties/AssemblyInfo.cs
- Test/ExtensionTest.cs
* added; `Open` state to `Subscription` https://github.com/recurly/recurly-client-net/pull/126
* fixed; Subscription Pending integration test https://github.com/recurly/recurly-client-net/pull/126
* fixed; referencing an `Invoice` from a `Subscription` returns the invoice https://github.com/recurly/recurly-client-net/pull/123
also fixes type on extension test
> Bump to 1.2.7

- History.md
- Library/Client.cs
- Library/Recurly.csproj
- Test/App.config
- Test/Recurly.Test.csproj
- Test/packages.config
* Retargeting .net v4.5 so we can use TLS headers.
* Adding explicit TLS 1.2 and 1.1 settings.
> Retargeting .NET v4.5

- History.md
- Library/Properties/AssemblyInfo.cs
* Retargeting to .NET version 4.5 for TLS headers [PR](https://github.com/recurly/recurly-client-net/pull/129)
* added; explicit TLS 1.2 and 1.1 settings [PR](https://github.com/recurly/recurly-client-net/pull/129)
* fixed; `Add(planAddOnCode, quantity)` method of `SubscriptionAddOnList` [PR](https://github.com/recurly/recurly-client-net/pull/128)
> bump to 1.3.0

- Library/AddOn.cs
- Library/Plan.cs
This is to address https://github.com/recurly/recurly-client-net/issues/140
This ensures that PlanCode can be publicly set and will be set when an addon is fetched so it can be updated. 
Ideally we would not expose the `PlanCode` setter here. This is something I can find a workaround for or something i can revert in the follow up PR.
We really should do a follow up where we change the Update() methods to use the resource's hrefs (which we should also be reading from xml) that way the resources don't have to track all of their parent resources and we don't need to encode routing logic into the objects. I'm going to do a follow up PR for that https://github.com/recurly/recurly-client-net/issues/142
> Set AddOn#PlanCode for GetAddOn

- Library/Account.cs
- Test/AccountTest.cs
Addresses https://github.com/recurly/recurly-client-net/issues/144
Verify the attribute can be set and read from xml
```csharp
var account = new Account("myaccountcode")
{
Email = "test@email.com",
FirstName = "John",
LastName = "Smith",
CcEmails = "cc1@email.com,cc2@email.com"
};
account.Create();
var fetchedAccount = Accounts.Get("myaccountcode");
Console.WriteLine(fetchedAccount.CcEmails);
```
> Adding cc_emails attribute to Account class

- .travis.yml
- Library/Client.cs
- Library/Recurly.csproj
The release build did not contain the line of code with TLS preferences due to these constants not being present. Was discovered by a report from @rafdizzle86 and decompiling the nuget package :/
In order to test, build a release then decompile and check that this line is present: https://github.com/recurly/recurly-client-net/blob/master/Library/Client.cs#L37
> Fix TLS preferences for releases

- Library/Account.cs
- Library/AddOn.cs
- Library/Adjustment.cs
- Library/BillingInfo.cs
- Library/Configuration/Settings.cs
- Library/Coupon.cs
- Library/CouponRedemption.cs
- Library/Invoice.cs
- Library/Plan.cs
- Library/Subscription.cs
- Library/Transaction.cs
Updating to API version 2.2
I had to add support for `updated_at` in the appropriate places. I'd like to also add usage based billing but I think that might take some more time and I want to assess the demand. This is good enough to unblock us and get us to version 2.3.
> Update to API version 2.2

- History.md
- Library/Transaction.cs
Regarding #158, this adds a `PaymentMethod` attribute on `Transaction`. It also cleans up a bunch of extra whitespace.
cc/ @bhelx
```csharp
var transaction = new Transaction("account_code", 100, "USD");
transaction.PaymentMethod = "credit_card";
transaction.Create();
Console.WriteLine(transaction.PaymentMethod);
```
> Adding `PaymentMethod` attribute on `Transaction`

- Library/Client.cs
- Library/Error.cs
I found this missing case for HTTP status code 400. It's possible this is being misapplied on the server but we should handle it nonetheless.
> Add error case for 400 status code

- Library/Configuration/Settings.cs
- Library/Configuration/SettingsManager.cs
- Library/Recurly.csproj
- Test/List/AccountListTest.cs
- Test/Recurly.Test.csproj
- Test/SettingsFixture.cs
- Test/SettingsManagerTest.cs
I have updated the settings component so it now does not load the settings by default, and allows you to specify how you load the config. I am looking for feedback if this is the direction being thought of and how it could be adjusted to fit more inline with your library.
The use case would now be inline with other libraries work where you either tell it to load from config, or inject the settings via parameters..
Usage would be to call one of the following when the app starts up.
```c#
Recurly.Configuration.SettingsManager.Initialize("api", "subdomain", "private", 100);
-or-
Recurly.Configuration.SettingsManager.InitializeFromConfig()
```
This would be a breaking change as it doesn't load from the config file by default in the current state, it may be preferred to try and load that so …
> WIP: Update to config with API Access

- History.md
- Library/Properties/AssemblyInfo.cs
This brings us up to API v2.3
* Exposed subscription 'PlanCode' publicly #139
* Set AddOn#PlanCode for GetAddOn #141 
* Fix TLS preferences for releases #143 
* Adding cc_emails attribute to Account class #147 
* Fixed Get Adjustment and related test #150 
* Add Currency attribute to BillingInfo #151 
* Update to API version 2.2 #154 
* Adding `PaymentMethod` attribute on `Transaction` #159 
* Update to config with API Access #162 
* Add error case for 400 status code #164 
* Usage Based Billing Support #165
> Bump 1.4.0

- Library/Usage.cs
Addresses issue #170
```csharp
// UsageTimestamp can be null now
var usage = new Usage(subscription.Uuid, addon.AddOnCode)
{
Amount = 100,
MerchantTag = "100 Marketing emails sent by the customer",
//RecordingTimestamp = DateTime.Now,
//UsageTimestamp = DateTime.Now,
};
usage.Create();
Console.WriteLine(usage);
Console.WriteLine(usage.UsageTimestamp);
```
> Allow null UsageTimestamp (defaults to server time)

- History.md
- Library/Properties/AssemblyInfo.cs
* New server feature: Allow `UsageTimestamp` to be null (and default to the server time) https://github.com/recurly/recurly-client-net/issues/170
> Bump 1.4.2

- History.md
- Library/Subscription.cs
Addresses issue #155 
```csharp
// some account with billing info
var account = Accounts.Get("e0004e3c-216c-4254-8767-9be605cd0b03");
// any plan
var plan = Plans.Get("bukbu0i2b2");
// make a sub and set collection method to manual
var subscription = new Subscription(account, plan, "USD"); // account, plan, currency
subscription.CollectionMethod = "manual";
// it used to blow up here because NetTerms was not set
subscription.Create();
Console.WriteLine(subscription.Uuid);
Console.WriteLine(subscription.NetTerms);
```
> Allow null NetTerms

- Library/Subscription.cs
Create a non manual Subscription and set PoNumber, it should come back:
```csharp
var account = Accounts.Get("5fe32e112b724061bbe210200c86c97b");
var plan = Plans.Get("gold1");
var subscription = new Subscription(account, plan, "USD"); // account, plan, currency
// don't set to manual
//subscription.CollectionMethod = "manual";
subscription.PoNumber = "12397129837";
subscription.Create();
Console.WriteLine(subscription.PoNumber); // 12397129837
```
> Make po_number always available to write on Subscription

- Library/Account.cs
- Library/Invoice.cs
Adds Invoice Create and Preview which allows sending all the invoice data on create and preview: 
https://dev.recurly.com/docs/post-an-invoice-invoice-pending-charges-on-an-acco
https://dev.recurly.com/docs/preview-an-invoice
```csharp
var account = Accounts.Get("5fe32e112b724061bbe210200c86c97b");
var adjustment = account.NewAdjustment("USD", 5000);
adjustment.Create();
var invoice = new Invoice();
invoice.CollectionMethod = "manual"; // manual or automatic
invoice.NetTerms = 10; // only sent when manual
invoice.VatReverseChargeNotes = "Vat notes";
invoice.CustomerNotes = "customer notes";
invoice.TermsAndConditions = "terms and conditions";
invoice.PoNumber = "70115";
invoice.Preview(account.AccountCode); // takes an account code
Console.WriteLine(invoice.TotalInCents); …
```
> Add Invoice Create and Preview data

- Library/Adjustment.cs
When calling subscription.Preview() I got the below exception due to an empty date field on Adjustment (called by Invoice Preview). The reason is that StartDate and UpdatedAt are trying to read directly as DateTime without checking if it is possible, like EndDate and CreatedAt does already. Just updated StartDate and UpdatedAt to the same pattern.
'subscription.Preview()' threw an exception of type 'System.FormatException'
Data: {System.Collections.ListDictionaryInternal}
HResult: -2146233033
HelpLink: null
InnerException: null
Message: "The string '' is not a valid AllXsd value."
Source: "System.Xml"
StackTrace: "   at System.Xml.Schema.XsdDateTime..ctor(String text, XsdDateTimeFlags kinds)\r\n   at System.Xml.XmlConvert.ToDateTime(String s, XmlDateTimeSerializationMode …
> Fix null Datetime Xml reading for Adjustment StartDate and UpdatedAt

- Library/Plan.cs
- Test/PlanTest.cs
`total_billing_cycles` was not included in the reader
> Add total_billing_cycles reader

- Library/BillingInfo.cs
Resolves #208 
Make sure we are writing the amazon `billing_agreement_id`. We are already reading it here https://github.com/recurly/recurly-client-net/blob/master/Library/BillingInfo.cs#L279
> Write amazon_billing_agreement_id

- Library/BillingInfo.cs
- Library/Invoice.cs
- Library/List/TransactionList.cs
- Library/Transaction.cs
Related to #211
I've gone through and checked all the enums to make sure they are up to date with what is on the server models. Hopefully this fixes these errors for a while. Any new enum values will be on a future API version release and old versions of the client should be protected from them.
> Add missing enum values

- Library/Account.cs
- Library/Coupon.cs
- Library/FilterCriteria.cs
- Library/List/RecurlyList.cs
- Library/MeasuredUnit.cs
- Library/Plan.cs
- Library/Recurly.csproj
- Library/Subscription.cs
- Library/Transaction.cs
- Library/Usage.cs
I'm starting this new branch to implement the new sorting parameters in API version 2.4: https://dev.recurly.com/docs/pagination
I'm looking for some feedback as the interface on this first draft feels pretty awkward. I want to keep backwards compatibility if possible but I'm willing to deprecate some methods.
This is what I did with Java for reference: https://github.com/killbilling/recurly-java-library/pull/142
\cc @1TheMuffinMan 
```csharp
try {
var filter = FilterCriteria.Instance
.WithOrder(FilterCriteria.Order.Desc)
.WithSort(FilterCriteria.Sort.CreatedAt)
.WithBeginTime(new DateTime(2015, 1, 1))
.WithEndTime(DateTime.UtcNow);           
var accounts = Accounts.List(Account.AccountState.Active, filter);
foreach (var account in accounts)
{
Console.WriteLine(account.AccountCode); …
```
> Sorting and Filtering parameters

- Library/Plan.cs
Resolves #226 
The presence of this field was causing problems when creating plans. To verify it's fixed, just create a Plan:
```csharp
class Program
{
static void Main(string[] args)
{
try
{
var recurlyPlan = new Plan("newcode", "newname");
recurlyPlan.UnitAmountInCents.Add("USD", 10000);
recurlyPlan.Create();
} catch (ValidationException ex)
{
foreach(Error err in ex.Errors)
{
Console.WriteLine(err.ToString());
}
}
#if DEBUG
Console.WriteLine("Press enter to close...");
Console.ReadLine();
#endif
}
}
```
> Remove trial_requires_billing_info, it's actually in 2.6

- History.md
- Library/Properties/AssemblyInfo.cs
Only contains 1 bug fix
* Removing `trial_requires_billing_info` from Plan (which is in api 2.6) #227 [issue #226]
> Bump 1.4.13

- Library/Account.cs
- Library/Coupon.cs
- Library/Subscription.cs
- Library/Transaction.cs
- Library/Usage.cs
- Test/PlanTest.cs
Replaces the filter override code in List() functions with a similar code construct that avoids the NullReferenceException caused by calling filter.Equals(null). This error might be specific to newer .NET framework versions but it hobbles much of the functionality in the current packaged release.
> Fixing NullReferenceException in List() functions

- Library/Client.cs
- Library/List/RecurlyList.cs
- Test/InvoiceTest.cs
- Test/List/AccountListTest.cs
- Test/SubscriptionTest.cs
We forgot to remove parsing of this header.
I think we will also need something in the release notes saying that you can no longer use the `Capacity` method on `RecurlyList`.
> Remove x records header

- History.md
- Library/Client.cs
- Library/List/RecurlyList.cs
- Library/Properties/AssemblyInfo.cs
- Test/InvoiceTest.cs
- Test/List/AccountListTest.cs
- Test/SubscriptionTest.cs
Going to hold off on this release until I can figure out how to make make this work with removal of `X-Records`
* Added account balance endpoint  #234 (issue #233)
* Added plan and subscription changes  #232
* Fixing NullReferenceException in List() functions  #231
* Fixed a probable NRE in Plans.List() #230
* Remove X-Records header #236 
This release will upgrade us to API version 2.6. There are two breaking changes:
1. To speed up your listing requests we’re no longer automatically computing the record counts for each requests. For our larger sites this could halve the response time. So in this release, we are removing the `RecurlyList#Capacity` method.
to be cached for you. For more info see [PR #324](https://github.com/recurly/recurly-client-ruby/pull/324).
2. For `POST …
> Bump 1.5.0

- Library/Adjustment.cs
- Library/Configuration/Settings.cs
- Library/GiftCard.cs
- Library/Invoice.cs
- Library/Purchase.cs
- Library/Recurly.csproj
- Library/Subscription.cs
- Library/packages.config
- Test/InvoiceTest.cs
Bumps us to API v2.7 and implements the `/purchases` endpoint.
```csharp
var accountCode = "benjamin-du-monde";
var currency = "USD";
var planCode = "surveillance-pro";
var couponCode = "surveillance-podcast-promo";
var giftCardRedemptionCode = "8Z5VE6IRMWJDHU4P";
// We can create a purchase object from an account code or an Account object (first argument).
// Use the Account object when you want create a new account. This works similar to Subscription.
var purchase = new Purchase(accountCode, currency);
// Add multiple adjustments (optional if subscription[s] included)
purchase.Adjustments.Add(new Adjustment(4000, "HD Camera", 5));
purchase.Adjustments.Add(new Adjustment(1000, "Motion Sensor", 10));
// Add multiple subscriptions (optional if adjustment[s] included) …
```
> Bump API v2.7 / purchases endpoint

- History.md
- Library/Properties/AssemblyInfo.cs
This bumps the library version to 1.6.0. A Nuget release and doc updates will follow.
* Gift Card Support #241 
* Purchases Endpoint Support #240 
This release will upgrade us to API version 2.7. There is only 1 breaking change in this library.
`Invoice` will now use an enum for the `CollectionMethod` property instead of a string. The enum has 2 values (Automatic and Manual). Example:
```csharp
// Setting
invoice.CollectionMethod = Invoice.Collection.Manual;
// Getting
if (invoice.CollectionMethod == Invoice.Collection.Automatic)
{
// do something
}
```
> Bump 1.6.0

- Library/Purchase.cs
This change is for the `api_version_2_8` branch. It allows you to set custom invoice notes on the purchase.
> Purchases Notes Changes

- History.md
- Library/Configuration/Settings.cs
- Library/Properties/AssemblyInfo.cs
- Library/Purchase.cs
- Library/Subscription.cs
* ImportedTrial flag on Subscription [PR](https://github.com/recurly/recurly-client-net/pull/247)
* Purchases Notes Changes [PR](https://github.com/recurly/recurly-client-net/pull/246)
This release will upgrade us to API version 2.8.
There is one breaking change in this API version you must consider. All `country` fields must now contain valid [2 letter ISO 3166 country codes](https://www.iso.org/iso-3166-country-codes.html). If your code fails validation, you will receive a validation error. This affects anywhere and address is collected.
> Bump 1.7.0

- Library/Plan.cs
We should not render this xml element unless it is set to something. It was being rendered `false` even when not being set.
> Make TrialRequiresBillingInfo an optional

- Library/AddOn.cs
- Library/Adjustment.cs
- Library/Plan.cs
- Library/Subscription.cs
- Library/SubscriptionAddOn.cs
Allows you to set and read RevenueScheduleTypes with the enum `Adjustment.RevenueSchedule`. Example:
```csharp
var plan = new Plan("gold12345", "Gold plan"); // plan code, name
plan.UnitAmountInCents.Add("USD", 1000);
plan.SetupFeeInCents.Add("USD", 6000);
plan.PlanIntervalLength = 1;
plan.PlanIntervalUnit = Plan.IntervalUnit.Months;
plan.RevenueScheduleType = Adjustment.RevenueSchedule.Evenly;
plan.SetupFeeRevenueScheduleType = Adjustment.RevenueSchedule.AtRangeEnd;
plan.Create();
Console.WriteLine(plan.SetupFeeRevenueScheduleType.ToString());
Console.WriteLine(plan.RevenueScheduleType.ToString());
```
> Implements missing `revenue_schedule_type`

- History.md
- Library/Properties/AssemblyInfo.cs
* Adds giftcard redeem endpoint #250 (Issue #249)
* Update the README with `Overview` section #251 
* Make TrialRequiresBillingInfo an optional #252 
* Implements missing `revenue_schedule_type` #253 
There is one small breaking change in this API version. `TrialRequiresBillingInfo` is now an optional so you will have to unwrap it to use it.
> Bump 1.8.0

- Library/AddOn.cs
- Library/GiftCard.cs
- Library/Plan.cs
- Library/Usage.cs
Some code were handling optional integer properties in ways that breaks expected behavior. In order to test if the programmer "set" the integer, it was checked against the default `0`. This has the means that you cannot set the value to 0. Example:
```csharp
var planCode = "aPlanCode";
var plan = Plans.Get(planCode);
 
Console.WriteLine(plan.TrialIntervalLength);
Console.WriteLine(plan.TrialIntervalUnit);
plan.TrialIntervalUnit= Plan.IntervalUnit.Months;
plan.TrialIntervalLength = 0;
plan.TrialRequiresBillingInfo = true;
plan.Update();
var updatedPlan = Plans.Get(planCode);
Console.WriteLine(updatedPlan.TrialRequiresBillingInfo);
Console.WriteLine(updatedPlan.TrialIntervalLength);
Console.WriteLine(updatedPlan.TrialIntervalUnit);
```
There are also cases where the xml elements are null …
> Make optional ints nullable

- Library/List/InvoiceList.cs
Right now when the API returns an empty list of invoices, the library parses it as a list with one empty invoice.
> Fix creation of an empty invoice when InvoiceList is empty

- History.md
- Library/Properties/AssemblyInfo.cs
- Add missing 'DinersClub' credit card type #258
- Fix creation of an empty invoice when InvoiceList is empty #260 
- Make optional ints nullable #263
- API v2.9 changes #264
- Fix revenue_schedule_type spelling #265
> Bump 1.9.0

- Library/Errors.cs
A NullReference exception is getting thrown inside the Exception class due a default instance not being set. 
The RecurlyException class is expecting that the passing parameter is always initialized but this is not always the case: 
The exception gets triggered when an exception occurs trying parse the XML response here:
The NullReference exception is masking other errors occurring in the consumer so this fix will ensure a default instance is always set.
> Set Errors variable to a default instance of the Errors class.

- History.md
- Library/Properties/AssemblyInfo.cs
Some bug fixes for 1.9:
- Set errors variable to a default instance of the Errors class #271 
- Handle empty revenue_schedule_type #270
> Bump 1.9.1

- Library/List/SubscriptionAddOnList.cs
- Library/SubscriptionAddOn.cs
- Test/ExtensionTest.cs
- Test/List/SubscriptionAddOnListTest.cs
- Test/SubscriptionTest.cs
When we create a usage addon whose usage type is percentage, the UnitAmountInCents is not required; the mandatory value is the percentage for the addon. In recurly administration console when you select the usage type by percentage, the UnitAmountInCents fields are not shown. 
The problem we saw in "SubscriptionAddOn" and "SubscriptionAddOnList" classes, is that when managing the addons some exceptions are thrown because they are accessing the UnitAmountInCents always, in spite of the fact that the addons have that value as null, because they are defined as percentage (UnitAmountInCents is not needed)
> fix unit amounts exceptions when using percentage addons

- Library/Coupon.cs
Resolves #274 
The problem is that using `int` for Coupon.Id was working when the ints were smaller. Once they got too large, the integer parser was failing to parse them. Should have been a `long` to begin with. All other resources that use druuid ids  use `long`.
> Change Coupon.Id from int to long

- History.md
- Library/Properties/AssemblyInfo.cs
- Fix unit amounts exceptions when using percentage addons #268 
- Add filter to InvoiceList, redemption updated_at #277
- Changed Coupon.Id from int to long #278 
- Implement Account Acquisition #279 
There is one very small breaking change. Coupon.Id changed from an `int` to a `long`. Your code will require a change if you explicitly reference it as an int.
> Bump 1.10.0

- History.md
- Library/Properties/AssemblyInfo.cs
- API v2.10 #281 
This includes the changes needed for API version 2.10. There are a few breaking changes:
When creating or failing invoices, we now return an InvoiceCollection object rather than an Invoice. If you wish to upgrade your application without changing functionality, we recommend that you use the `ChargeInvoice` property on the InvoiceCollection to get the charge Invoice. Example:
```csharp
// Change this:
var invoice = account.InvoicePendingCharges();
// To this
var invoiceCollection = account.InvoicePendingCharges();
var invoice = invoiceCollection.ChargeInvoice;
// Invoice.MarkFailed now returns a new collection
// Change this
invoice.MarkFailed();
// To this
var invoiceCollection = invoice.MarkFailed();
var failedInvoice = invoiceCollection.ChargeInvoice;
```
If you want …
> Bump 1.11.0

- Library/Subscription.cs
Hi, when I try to pause a subscription, I get an error from the server that the field 'remaining_pause_cycles' is required. After these changes, the pause is working.
> fix typo in Subscription#pause

- Library/BillingInfo.cs
- Test/BaseTest.cs
- Test/BillingInfoTest.cs
Resolves #292
Now includes the `company` field when writing the XML for updating a `BillingInfo` instance.
Also added a `Debug` statement to identify any unhandled fields during reading of XML (noticed that `currency` field isn't currently included but don't think that can be tested unless the environment is configured for multi-currency).
Related tests expanded to include all relevant `BillingInfo` properties.
> Fix missing `company` field when updating `BillingInfo` instances

- Library/List/SubscriptionAddOnList.cs
- Library/SubscriptionAddOn.cs
We are getting the following error when we try to create a new subscription with a Usage addon type:
Message: {usagePriceInDecimalUnits is not allowed when PricingType is USAGE. | Field: "subscription.base" Code: "" Symbol: "field_mismatch_not_allowed" Details: ""} 
The problem is that the field unitamountincents was being provided with 0 automatically. With this pull request fix this error.
Regards,
> Fix unit amount in cents for usage add ons

- History.md
- Library/Properties/AssemblyInfo.cs
* Fix unit amount in cents for usage add ons #298 
* Expose subs accountcode to avoid unnecessary api requests #296 
###Upgrade Notes 
`SubscriptionAddOn#UnitAmountInCents` was changed to nullable type. If you do not read this value, no change is needed.
> Bump 1.12.0

- Library/Purchase.cs
For API version 2.13. Allows programmer to set the gateway for a purchase. If this changes, I will follow up with another PR on the `api_version_2_13` branch.
> Allow programmer to set gateway per purchase

- Library/Invoice.cs
For API version 2.13. If the invoice has over 500 transactions, the programmer should use this endpoint.
> Add link to all transactions

- Library/Account.cs
- Library/BillingInfo.cs
- Library/Transaction.cs
The Transaction class was only parsing links to accounts. We want to parse the embedded Account if it's embedded (since it may contain a snapshot of information). We also want to parse the embedded BillingInfo in Account if it exists for similar reasons.
Testing:
```csharp
var transaction = Transactions.Get("4573206f388c4eb391da9d42109329437");
Console.WriteLine(transaction.Account.AccountCode);
Console.WriteLine(transaction.Account.BillingInfo.CardType);
```
> Transaction should parse embedded account

- Library/List/UsageList.cs
- Library/Usage.cs
Resolves #304 
I've adapted the code initially reported to test this:
```csharp
var subUuid = "4568de9b86ec93f7a875e446aca2f694";
var addonCode = "usage-code";
var quantity = 1;
var usage = new Recurly.Usage(subUuid, addonCode);
usage.Amount = quantity;
usage.Create();
var usages = Recurly.Usages.List(subUuid, addonCode);
usage = usages.FirstOrDefault();
usage.Amount = quantity;
usage.Update();
> Fix usages Id parsing bug

- Library/Coupon.cs
- Library/Subscription.cs
- Test/CouponTest.cs
- Test/SubscriptionTest.cs
- Test/TestEnvironment.cs
Addresses https://github.com/recurly/recurly-client-net/issues/312 where Subscription.Coupon would fail if the underlying coupon code was null.
* Updates `Coupons.Get(couponCode)` to return null when the provided couponCode is null or whitespace, preventing a call to Recurly. 
* Updates `Subscription.Coupon` to return null if `_couponCode` is null or whitespace.  However, this does not set the underlying `_coupon` object in the event `_couponCode` is updated elsewhere.
* Adds `TestEnvironment.Type.Unit` for tests, since the tests added do not rely on a web call out.
* Adds tests to `CouponTest` that verifies null is returned for the three scenarios provided, and that the functionality remains consistent.
* Adds tests to `SubscriptionTest` to verify that `Subscription` will receive null, …
> #312 - Subscription.Coupon throws an ArgumentNullException, if _couponCode is null

- History.md
- Library/Properties/AssemblyInfo.cs
This release brings us to API version 2.13 but does not have any breaking changes.
* Allow programmer to set gateway code per purchase #303 
* Add link to all_transactions on Invoice #302 
* Subscription Terms #311 
* Subscription.Coupon throws an ArgumentNullException, if _couponCode is null. Now returns null. #313
> Bump 1.12.2

- Library/Account.cs
- Library/BillingInfo.cs
This PR allows `CardType`, `Month`, and `Year` to be null. It prevents exceptions when parsing.
> Allow more nulls in BillingInfo

- .travis.yml
Upgrades mono to 4.8 to fix the failing tests.
> Upgrade mono to fix TLS issue

- Library/Account.cs
- Library/CustomField.cs
- Library/Recurly.csproj
- Library/Subscription.cs
- Test/AccountTest.cs
- Test/SubscriptionTest.cs
Adds custom fields support to Account and Subscription. This also works when embedding them in a Purchase.
```csharp
var account = Accounts.Get("c4ac4481");
foreach (var f in account.CustomFields)
{
Console.WriteLine(f.Name);
Console.WriteLine(f.Value);
}
// Setting the value to null will clear the field
//account.CustomFields[0].Value = null;
account.CustomFields[0].Value = "new-value";
// Add a new custom field
account.CustomFields.Add(new CustomField("topping", "lettuce"));
account.Update();  
```
> 2.13 Custom Fields Support

- Library/Recurly.csproj
- Test/Recurly.Test.csproj
The AllRules.ruleset file does not exist in the project and does not exist in the .gitignore file. I'm not sure why this was in there, but it causes an unnecessary compiler warning.
> Remove reference to unused ruleset

- Library/Subscription.cs
- Test/SubscriptionTest.cs
The changes at lines 332, 338, 347, 352 and 358 remove an invisible character that is unrecognized by OSX. Since it's all in the comments, I figured it's not a problem to remove that character.
> Allow updating custom fields through /notes endpoint

- scripts/test
Allows use of `./scripts/test Debug TestClass.TestMethod` or `./scripts/test Release TestClass.TestMethod` or `./scripts/test TestClass.TestMethod` where TestClass is the name of a valid class in the Test directory, and TestMethod is a valid method name for that class.
> Allow test script to run a single method

- History.md
- Library/Properties/AssemblyInfo.cs
* Allow updating custom fields through /notes endpoint #328 
* Add ability to update an invoice #329 
* Remove reference to unused ruleset #326 
* Upgrade .NET 4.7 and scripts folder #327 
* Allow test script to run a single method #330 
* Fix integration tests so they all pass #332 
This release brings us up to API version 2.14. The build now targets .NET v4.7.
Please make sure that you update your application appropriately.
> Bump 1.13.0

- Library/BillingInfo.cs
Adds gateway_code, gateway_token, and card_type in billing info xml.
Playground script:
```C#
// Assumes account "x" exists on this site
// Assumes gateway_code "jhpqd551excn" is the code for vantiv on this site
using System;
using Recurly;
{
class CreateBillingInfo
{
{
var account = Accounts.Get("x");
info.FirstName = "John";
info.LastName = "Smith";
info.City = "San Fransisco";
info.State = "CA";
info.PostalCode = "90212";
info.GatewayToken = "4111115851581111";
info.GatewayCode = "jhpqd551excn";
info.CardType = BillingInfo.CreditCardType.Visa;
info.ExpirationMonth = 10;
info.ExpirationYear = 2020;
try
{
info.Create();
}
catch(RecurlyException …
```
> Add tokenization support for billing info

- Library/AddOn.cs
- Library/Client.cs
- Library/List/ShippingAddressList.cs
- Test/SubscriptionTest.cs
These commits fix 4 warnings the compiler complains about when building the project:
1. `List/ShippingAddressList.cs(52,21): warning CS0114: 'ShippingAddressList.Add(ShippingAddress)' hides inherited member 'RecurlyList<ShippingAddress>.Add(ShippingAddress)'.`
2. `AddOn.cs(7,18): warning CS0659: 'AddOn' overrides Object.Equals(object o) but does not override Object.GetHashCode()`
3. `Client.cs(44,13): warning CS0618: 'XmlTextReader.ProhibitDtd' is obsolete: 'Use DtdProcessing property instead.'`
4. `SubscriptionTest.cs(607,41): warning CS0168: The variable 'e' is declared but never used`
> Fix Compiler Warnings

- History.md
- Library/Configuration/Settings.cs
- Library/Properties/AssemblyInfo.cs
- dist/recurly.nuspec
1.13.1 (stable) / 2018-09-25
* Added clean and release scripts [PR](https://github.com/recurly/recurly-client-net/pull/336)
* Updated README with config and .Net target instructions [PR](https://github.com/recurly/recurly-client-net/pull/337)
* Fixed release script [PR](https://github.com/recurly/recurly-client-net/pull/339)
* Escape user supplied input [commit](https://github.com/recurly/recurly-client-net/commit/7a516e77c43f6993bc8b4d62a21336eed6e6bd6c)
* Check for empty and null strings [commit](https://github.com/recurly/recurly-client-net/commit/3823d7a0b0d68e6f7877eaca7bc87f784fc105ce)
* Fix compiler warnings [PR](https://github.com/recurly/recurly-client-net/pull/341)
> Bump to version 1.13.1 / API version 2.15

- Library/GiftCard.cs
Addresses a pain point touched on in #261  
- The properties RedeemedAt and DeliveredAt of the GiftCard class are now nullable.
> Make GiftCard RedeemedAt, DeliveredAt and CanceledAt nullable

- Library/Usage.cs
Fixes #338 
Playground script for testing. Be sure to change the sub UUID and Addon code to whatever your sandbox site uses. Tested with no updates to the recording time, using DateTimeKind.Utc as well as Local and Unspecified.
```C#
using System;
using Recurly;
using System.Linq;
{
class UpdateUsage 
{
{
var subscriptionUuid = "47c92b1ea14c0a67ed60fd4f01bded5f";
var subscriptionAddOnCode= "usage_based";
var quantity = 2;
var recTime = new DateTime(2018, 10, 10, 2, 30, 20, DateTimeKind.Local);
var usage = Recurly.Usages.List(subscriptionUuid, subscriptionAddOnCode).FirstOrDefault();
if(usage!=null)
{
usage.Amount = quantity;
usage.RecordingTimestamp = recTime;
usage.Update();
}
}
}
}
```
> Change formatting of Usage dates in WriteXML to match Recurly format

- History.md
- Library/Configuration/Settings.cs
- Library/Properties/AssemblyInfo.cs
- dist/recurly.nuspec
1.14.0 (stable) / 2018-10-30
* Made Gift Card RedeemedAt, DeliveredAt and CanceledAt nullable [PR](https://github.com/recurly/recurly-client-net/pull/343)
* Change Usage dates to UTC [PR](https://github.com/recurly/recurly-client-net/pull/345)
* Standardize line endings [PR](https://github.com/recurly/recurly-client-net/pull/346)
* Changed Invoice Refunds for Credit Memo API changes [PR](https://github.com/recurly/recurly-client-net/pull/347)
* Fixed tests based on credit memo changes [PR](https://github.com/recurly/recurly-client-net/pull/349)
This release brings us up to API version 2.16.
Refunding multiple adjustments requires use of the new Invoice#RefundOptions class.
> Bump to version 1.14.0 / API version 2.16

- Library/Account.cs
- Test/AccountTest.cs
Adds exemption_certificate attribute to the account object.
Script:
```c#
using System;
using Recurly;
{
class CreateAccount
{
{
var account = new Account("new-account");
account.TaxExempt = true;
account.ExemptionCertificate = "Some Certificate";
account.Create();
}
}
}
```
> Add ExemptionCertificate attribute to Account

- Library/Invoice.cs
- Library/Subscription.cs
- Test/InvoiceTest.cs
- Test/SubscriptionTest.cs
Adds GatewayCode to the Subscription object for the `/notes` endpoint. Also adds GatewayCode to the Invoice object for `PUT invoices`.
Scripts:
```c#
using System;
using System.Linq;
using Recurly;
using System.Collections.Generic;
{
class UpdateSubNotes
{
{
var subscription = Subscriptions.Get("4810fde9f3f29b244474e445d795cc78");
var dict = new Dictionary<string, string>();
dict.Add("GatewayCode", "jotgbnxnecn0");
subscription.UpdateNotes(dict);
}
}
}
```
```c#
using System;
using System.Linq;
using Recurly;
using System.Collections.Generic;
{
class UpdateInvoice
{
{
var invoice = Invoices.Get(1001);
invoice.GatewayCode = "jhpqd551evcn";
try
{
invoice.Update(); …
```
> Add GatewayCode to subscription for notes and invoice

- Library/Error.cs
- Library/Errors.cs
- Library/Exception.cs
- Library/InvalidCredentialsException.cs
- Library/NotFoundException.cs
- Library/ServerException.cs
- Library/TemporarilyUnavailableException.cs
- Library/TransactionError.cs
- Library/ValidationException.cs
Relates to issue https://github.com/recurly/recurly-client-net/issues/348.
Basically, aim is to be able to mock the Recurly errors from outside of the Recurly namespace. I did not make every constructor public but I made sure that every error exposed by Recurly had a public parameterless constructor. Beyond that, I wasn't sure what needed to actually remain as 'internal only'. 
After this change, the following worked for me:
```c#
namespace Foo.Bar 
{
public class CustomRecurlyTests
{
public void DoAnything()
{
var a0 = new Recurly.RecurlyException();
var a1 = new Recurly.InvalidCredentialsException();
var a2 = new Recurly.NotFoundException();
var a3 = new Recurly.ServerException();
var a4 = new Recurly.TemporarilyUnavailableException();
var a5 = new Recurly.TransactionError();
var a6 = …
```
> modified Error classes to have at least one public constructor

- Library/Account.cs
- Test/AccountTest.cs
This PR adds methods for working with shipping addresses, which for whatever reason were missing from this library. There was a `GetShippingAddresses` method already, but there was no way to create, update or delete a shipping address.
No script because example usage is in the test.
> Add methods for working with Shipping Addresses

- Library/Subscription.cs
There are two different `WriteXml` type functions on the Subscription object. The one for the `/notes` endpoint includes custom fields, but the one for the regular `/subscriptions` endpoint does not. This PR fixes that.
Script:
```C#
// Assumes "47852d1aefe69b0e9c69504d93ab46f9" is a valid subscription on the account
// Assumes "device_id" is a configured custom field on the account
class UpdateSubscription
{
{
var sub = Subscriptions.Get("47852d1aefe69b0e9c69504d93ab46f9");
sub.CustomFields.Add(new CustomField("device_id", "KIWTL-WER-ZXMRD"));
sub.ChangeSubscription();
}
}
}
> Add custom fields to WriteChangeSubscriptionXml

- Library/Invoice.cs
- Library/Transaction.cs
- Test/InvoiceTest.cs
This adds a method to handle this API endpoint https://dev.recurly.com/docs/enter-an-offline-payment-for-a-manual-invoice
The test pretty much shows example usage, but here's a script just in case:
```C#
using System;
using Recurly;
{
class EnterOfflinePayment
{
{
var account = new Account(System.Guid.NewGuid().ToString());
account.Create();
var adjustment = account.NewAdjustment("USD", 5000, "Test Charge");
adjustment.Create();
var newInvoice = new Invoice();
newInvoice.CollectionMethod = Invoice.Collection.Manual;
var invoice = account.InvoicePendingCharges(newInvoice).ChargeInvoice;
var offlineTransaction = new Transaction(account, 5000, "");
offlineTransaction.PaymentMethod = "credit_card";
offlineTransaction.CollectedAt = new …
```
> Add EnterOfflinePayment method to Invoice

- Library/Subscription.cs
Fixes #214 
The API assumes that all incoming dates are UTC. This change makes it an explicit UTC date string even if the user were to pass in a `DateTime` object with `DateTimeKind == Local` to `Subscription.Postpone()`.
Script:
```c#
using System;
using Recurly;
{
class PostponeSubscription
{
{
var sub = Subscriptions.Get("47852d1aefe69b0e9c69504d93ab46f9");
var date = new DateTime(2018, 12, 7, 12, 0, 0, DateTimeKind.Local);
sub.Postpone(date);
}
}
}
```
> Make UTC explicit in Subscription.Postpone

- History.md
- Library/Account.cs
- Library/Configuration/Settings.cs
- Library/Invoice.cs
- Library/Properties/AssemblyInfo.cs
- Library/Subscription.cs
- Test/AccountTest.cs
- Test/InvoiceTest.cs
- Test/SubscriptionTest.cs
- dist/recurly.nuspec
1.14.1 (stable) / 2018-12-11
This release brings us up to API version 2.17
* Add public constructors to error classes [PR](https://github.com/recurly/recurly-client-net/pull/350)
* Add missing values to WriteChangeSubscriptionXml() [PR](https://github.com/recurly/recurly-client-net/pull/352)
* Add `GatewayCode` to Subscription for notes and Invoice [PR](https://github.com/recurly/recurly-client-net/pull/355)
* Add `ExemptionCertificate` attribute to Account [PR](https://github.com/recurly/recurly-client-net/pull/356)
* Remove examples.md [PR](https://github.com/recurly/recurly-client-net/pull/357)
* Add Custom Fields to WriteChangeSubscriptionXml() [PR](https://github.com/recurly/recurly-client-net/pull/358)
* Add EnterOfflinePayment method to Invoice …
> Release version 2.14.1 / API version 2.17

- Test/AccountTest.cs
This test will always fail because it only works when Vertex is integrated on the account. This would be better as a unit test, but we don't have an XML mocking framework set up for tests like these in this library.
Honestly, I trust this works without a test.
> Remove broken test for ExemptionCertificate

- History.md
- Library/Recurly.csproj
- Library/Subscription.cs
- Library/SubscriptionAddOn.cs
- Library/SubscriptionChange.cs
- Test/EnumTest.cs
- Test/SubscriptionTest.cs
Fixes #157 
The pattern here is different from the patterns of this library, but I believe it will be an improvement because it makes all the changes you want to make explicit, rather than implicit. 
The developer must make a SubscriptionChange object, then any value that ought to be changed should be explicitly set on that object. This object can then be passed into the new static methods `PreviewChange()` and `ChangeSubscription()`, which will return the changed subscription in a new Subscription object.
Script:
```c#
using System;
using Recurly;
{
class PreviewSubscriptionChange
{
{
var change = new SubscriptionChange()
{
PlanCode = "gold"
};
var newSub = Subscription.PreviewChange("48e99881b3726425bf49e64b45af7fe4", change);
}
} …
```
> Add SubscriptionChange class

- .travis.yml
This adds the travis file for the v3 beta code. Going to try to get a matrix build running the tests.
Dotnet 1.1 is end-of-life in summer of 2019. I think we will stick with 2.1 and 2.2 support until we have a strong reason to add 1.1 support.
> Add travis file for 3.0.0 beta

- Library/BillingInfo.cs
This adds the new amazon_region attribute to the Billing Info class.
```C#
{
class CreateBillingInfo
{
{
var account = Accounts.Get("x");
info.FirstName = "Aaron";
info.LastName = "Du Monde";
info.City = "New Orleans";
info.State = "LA";
info.PostalCode = "70212";
info.AmazonBillingAgreementId = "C01-1234567-8901234";
info.AmazonRegion = "eu";
try
{
info.Create();
}
catch(RecurlyException e)
{
Console.WriteLine(e.Errors[0]);
}
}
}
}
```
> Add amazon_region to Billing Info

- Library/Address.cs
- Library/Error.cs
- Library/Exception.cs
- Library/Purchase.cs
While working on #367, I encountered several errors regarding the WriteXML of a few functions. This made me realize two things:
1) We're writing extra elements in the XML that are unnecessary, and we should really be checking for null before writing these elements.
2) The details of the errors are not written when logging the error in the following manner:
```c#
try
{
// something that will fail validation or transaction
}
catch(RecurlyException e)
{
Console.WriteLine(e);
}
```
It would be nice if when you log the error somewhere, you could go ahead and see what the details of the error are.
In debug mode, this was logged to my console BEFORE:
```
Recurly Library Received: 400 - BadRequest
Recurly.ValidationException: The information being saved is not valid.
at …
```
> Fix extra written elements and add error details to RecurlyException

- History.md
The original upgrade notes for version 1.14.0 were incorrect. When this PR is merged, we will also update the [Release tag](https://github.com/recurly/recurly-client-net/releases/tag/1.14.0) as well as the [.Net upgrade guide](https://dev.recurly.com/page/net-upgrade-guide)
> Fix upgrade notes for version 1.14.0

- History.md
- Library/Properties/AssemblyInfo.cs
- dist/recurly.nuspec
1.15.0 (stable) / 2019-02-05
* Bug fixes [PR](https://github.com/recurly/recurly-client-net/pull/368)
* Remove broken test [PR](https://github.com/recurly/recurly-client-net/pull/365)
* Add SubscriptionChange class [PR](https://github.com/recurly/recurly-client-net/pull/363)
* Update the User Agent [PR](https://github.com/recurly/recurly-client-net/pull/361)
* Add TransactionError property to Transaction class [PR](https://github.com/recurly/recurly-client-net/pull/372)
This release contains two breaking changes:
To update a subscription, a SubscriptionChange object must be passed into the `ChangeSubscription()` method.
See the C# example in our [dev docs](https://dev.recurly.com/docs/update-subscription).
In the past, if you were to leave a value such as `FirstName` null, …
> Release Version 1.15.0

- Library/SubscriptionAddOn.cs
Fixes #375 
This change reads the tag for `usage_percentage` as a string and then converts it to a float with Invariant culture format so it will be represented the same way regardless of locale settings.
> Fix issue when usage_percentage is null

- History.md
- Library/Properties/AssemblyInfo.cs
- dist/recurly.nuspec
1.15.1 (stable) / 2019-02-07
* Fix bug when SubscriptionAddOn.UsagePercentage is null [PR](https://github.com/recurly/recurly-client-net/pull/376)
> Release version 1.15.1

- History.md
- Library/BillingInfo.cs
- Library/Configuration/Settings.cs
- Library/Properties/AssemblyInfo.cs
- dist/recurly.nuspec
1.15.2 (stable) / 2019-02-19
This release brings us up to API version 2.18
* Add support for Amazon Region [PR](https://github.com/recurly/recurly-client-net/pull/369)
> Release version 1.15.2 / API version 2.18

- Library/List/SubscriptionAddOnList.cs
- Library/SubscriptionChange.cs
Fixes #379
There were some issues with how SubscriptionAddOns work in this library, and this attempts to fix those issues.
Example script:
```C#
// Assumes a subscription with uuid "4ac9897d06e86fddcbb62c4a02b54753" 
// exists on the account
var subscriptionUuid = "4ac9897d06e86fddcbb62c4a02b54753";
var change = new SubscriptionChange 
{ 
TimeFrame = SubscriptionChange.ChangeTimeframe.Now,
NetTerms = 30,
PoNumber = "12345",
AddOns = new SubscriptionAddOnList()
};
// Assumes an add on with code "ipaddresses" exists on the account
var addOnCode = "ipaddresses";
var quantity = 1;
var amountInCents = 200;
change.AddOns.Add(addOnCode, quantity, amountInCents);
Subscription.ChangeSubscription(subscriptionUuid, change);
```
> Fix Subscription Change issues regarding AddOns

- Recurly.Tests/ClientTest.cs
- Recurly.Tests/JsonSerializerTest.cs
- Recurly/BaseClient.cs
- Recurly/JsonSerializer.cs
- Recurly/Resources/Coupon.cs
Two changes here:
1. Remove Coupon#Plans. The API is returning both strings and Lists for this property. This won't be fixed until 2018-10-04.
2. No longer display warnings for serialization errors, instead we should throw an exception.
> Fix coupon parsing bug

- Recurly/BaseClient.cs
This allows reconfiguring the base api url for testing purposes. I tried to make it as unattractive and awkward as possible.
> Allow configurable api url

- Library/SubscriptionChange.cs
This adds support for updating the subscription at next bill date rather than just immediately or at renewal.
```C#
var subChange = new SubscriptionChange()
{
TimeFrame = SubscriptionChange.ChangeTimeframe.BillDate
};
subChange.PlanCode = "gold";
Subscription.ChangeSubscription("4c2a90c55cfe520e7f33744dc09ae922", subChange);
```
> Add support for At Next Bill Date

- Library/Client.cs
- Library/Configuration/Section.cs
- Library/Configuration/Settings.cs
- Library/Configuration/SettingsManager.cs
- README.md
- Test/SettingsManagerTest.cs
Add a timeout configuration to allow the user to overwrite the default timeout for an httpWebRequest.
> Add a Timeout Configuration.

- History.md
- Library/Configuration/Settings.cs
- Library/List/ShippingMethodList.cs
- Library/Properties/AssemblyInfo.cs
- Library/Purchase.cs
- Library/Recurly.csproj
- Library/ShippingFee.cs
- Library/ShippingMethod.cs
- Library/Subscription.cs
- Library/SubscriptionChange.cs
- dist/recurly.nuspec
1.15.6 (stable) / 2019-05-21
This release brings us up to API version 2.20. There are no breaking changes.
* Add Default Request Timeout Setting [PR](https://github.com/recurly/recurly-client-net/pull/395)
* Add Shipping Fees [PR](https://github.com/recurly/recurly-client-net/pull/396)
* Allow updating a subscription at next bill date [PR](https://github.com/recurly/recurly-client-net/pull/397)
> Release version 1.15.6

- Recurly/BaseClient.cs
- Recurly/Pager.cs
- Recurly/Utils.cs
This ensures the query params that were passed to the pager builder are used. Even though RestSharp handles some of this for the BaseClient, I decided to share the implementation in Utils.QueryString so there weren't 2 places where we have to do the casting and encoding.
We might change this interface in the future to support a `PaginationOptions` object or something similar instead of all of these arguments. For now, let's make this work.
Example use:
```csharp
// set page size to 200 and begin time to 2019/04/01 
var accounts = client.ListAccounts(null, 200, null, null, new DateTime(2019, 4, 1));
foreach(var account in accounts)
{
Console.WriteLine(account.Code);
}
```
> Implement pagination params

- README.md
- Recurly.Tests/PagerTest.cs
* Update paginate by page examples. Don't need to reassign the pager object since it returns this. This interface was not implemented.
* Add test for this example just for assurances.
> Update pagination doc

- History.md
- Library/Properties/AssemblyInfo.cs
- dist/recurly.nuspec
1.15.7 (stable) / 2019-06-18
* Allow programmer to change the PlanCode [PR](https://github.com/recurly/recurly-client-net/pull/414)
> Bump to version 1.15.7

- Library/BillingInfo.cs
- Library/TransactionError.cs
- Library/TransactionErrorEnum.cs
This allows the client to use the new 3DSecure features of the API. This involves a 2 step flow with RecurlyJS, see https://github.com/recurly/recurly-js/pull/527 for technical details on that side of this process.
Script 1: Attempt to update a billing info with a credit card that requires 3DS authentication:
```C#
var account = Accounts.Get("x");
info.FirstName = "Aaron";
info.LastName = "Du Monde";
info.City = "New Orleans";
info.State = "LA";
info.PostalCode = "70212";
info.CreditCardNumber = "4000000000003220";
info.ExpirationMonth = 10;
info.ExpirationYear = 2020;
try
{
info.Create();
}
catch(RecurlyException e)
{
if (e.TransactionError.ErrorCodeEnum == …
```
> Add 3DS tokens to transaction error and billing info

- Library/BillingInfo.cs
Hi,
I have experienced an issue when retrieving invoices for a particular account. I have submitted to support (see ticket 447037). 
It seems that the XML returned by the api has 'account_type' field as a null value. The SDK then fails with 'Cannot convert a null or empty string to an Enumeration'. 
The submitted patch will only try to parse the account_type field as an enum if the account_type field has a value.
Thanks
> Accommodate null value in Bank Account Type

- Library/Configuration/Section.cs
- Test/SettingsManagerTest.cs
Fixes #417 
The problem was both that the property needed to be changed to `timeoutMilliseconds` and that defaulting to `null` would result in another NullReferenceException. This fixes both of those problems, and adds a test around the configuration file so we'll hopefully catch this if something changes again.
> Fix timeoutMilliseconds when using config file

- Library/Account.cs
- Library/Adjustment.cs
This adds missing properties to the XML serializer of the `Adjustment` class.
Script:
```C#
var account = Accounts.Get("x");
var adjustment = account.NewAdjustment(
"USD",                        // currency
5000,                         // unit_amount_in_cents
"Charge for extra bandwidth", // description
1,                            // quantity
"bandwidth",                  // accounting_code
false                         // tax_exempt
);                       
adjustment.RevenueScheduleType = Adjustment.RevenueSchedule.AtInvoice;
adjustment.StartDate = new DateTime(2019, 6, 11);
adjustment.EndDate = new DateTime(2019, 7, 11);
adjustment.Create();
```
> Add missing properties to NewAdjustment method

- Library/Address.cs
- Library/Invoice.cs
When updating an invoice, more XML elements are written than what was actually changed. This can cause problems if, for example, a site has taxes enabled and an invoice is previously taxed (meaning that the address cannot be updated).
Suppose you want to update the invoice PO number. The XML should look like this:
```xml
<?xml version="1.0" encoding="utf-8"?>
<invoice>
<po_number>1-I1</po_number>
</invoice> 
```
Currently, an Address object is also sent with the invoice update, like so:
```xml
<?xml version="1.0" encoding="utf-8"?>
<invoice>
<address>
<first_name>Aaron</first_name>
<last_name>Du Monde</last_name>
<name_on_account />
<company />
<address1>900 Camp St.</address1>
<address2 />
<city>New Orleans</city>
<state>LA</state>
<zip>70115</zip>
<country>US</country>
<phone /> …
```
> Only send Address object if Address properties were changed

- History.md
- Library/Properties/AssemblyInfo.cs
- Test/BillingInfoTest.cs
- dist/recurly.nuspec
1.16.0 (stable) / 2019-07-16
* Fix timeoutMilliseconds when using config file [PR](https://github.com/recurly/recurly-client-net/pull/420)
* Only send Address object if Address properties were changed [PR](https://github.com/recurly/recurly-client-net/pull/426)
* Add missing properties to XML serializer for Adjustment class  [PR](https://github.com/recurly/recurly-client-net/pull/427)
This release contains one breaking change:
When updating an Invoice, the embedded Address object is only sent to the API if explicitly set on the object, and the following fields require an empty string to clear values:
- CustomerNotes
- TermsAndConditions
- VatReverseChargeNotes
- GatewayCode
- PoNumber
In the past, if you were to leave a value such as `CustomerNotes` null, it would nullify …
> Bump to version 1.16.0

- README.md
We're sticking with the argument-based params for now. We'll just recommend the programmer use named arguments instead of positional arguments.
> Document pagination params

- Library/Account.cs
- Library/BillingInfo.cs
- Library/Invoice.cs
- Library/Purchase.cs
- Library/Subscription.cs
As a part of PSD2, there is an exemption to exclude MOTO transactions from SCA scope.
In order to pass this indicator to the gateways, merchants need a mechanism via API
to inform Recurly of these transactions. These transactions will be initiated from
within a merchants customer service / support admin portal UI, where the customer
is not authenticated to be able to complete an SCA flow.
This is exposed to the programmer as `transaction_type` on many of the resources. Set the value to `moto` to mark the transaction as MOTO. Ex use with purchases:
```csharp
var purchase = new Purchase("benjamin-du-monde", "USD";);
purchase.TransactionType = "moto";
purchase.Subscriptions.Add(new Subscription("gold"));
var collection = Purchase.Invoice(purchase);
```
> MOTO transactions

- History.md
- Library/Account.cs
- Library/BillingInfo.cs
- Library/Configuration/Settings.cs
- Library/Invoice.cs
- Library/Properties/AssemblyInfo.cs
- Library/Purchase.cs
- Library/Subscription.cs
- dist/recurly.nuspec
1.16.1 (stable) / 2019-08-21
This brings us up to API version 2.22. There are no breaking changes.
- MOTO transactions [PR](https://github.com/recurly/recurly-client-net/pull/437)
> Release 1.16.1 / API version 2.22

- README.md
- Recurly.Tests/BaseClientTest.cs
- Recurly.Tests/ClientTest.cs
- Recurly.Tests/PagerTest.cs
- Recurly/BaseClient.cs
- Recurly/Client.cs
- scripts/build
- scripts/format
- scripts/test
This removes the constraint of required site-id to initialize a client.
The site can be inferred from the api key. We will be adding ways to
use multiple sites with the same client in the future. This sets us
up so we can do that in a non-breaking way.
> Remove the site-id constraint from Client

- History.md
- Library/Properties/AssemblyInfo.cs
- dist/recurly.nuspec
1.16.2 (stable) / 2019-09-13
- PSD2 billing info changes [PR](https://github.com/recurly/recurly-client-net/pull/441)
> Release 1.16.2

- Recurly/Recurly.csproj
A few notable changes:
* Remove the site-id constraint from Client #440 
*  Implement bump script #443  
* Fix Pager empty page bug #432 [ Fixes #445 ]
* Add CONTRIBUTING.md #430
This PR also makes sure that symbols and the source code are included in the release in the form of a [.snupkg](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg) file. This should fix some of the difficulties with debugging as experienced with #445.
#440 contains a breaking change. `Recurly.Client` now only takes an api key (site id / subdomain is not needed). The type signature was changed from: `Recurly.Client(string siteId, string apiKey)` to `Recurly.Client(string apiKey)`
> 3.0.0-beta.6 Release

- Library/Subscription.cs
- Library/SubscriptionChange.cs
Adds term_end to the Timeframe values. This affects
Subscription#ChangeSubscription, Subscription#PreviewChange
and Subscription#Cancel.
Subscription#ChangeSubscription and Subscription#PreviewChange have been updated to no longer accept the Renewal timeframe.
Instead, merchants will be able to send timeframes of BillDate or TermEnd.
These timeframes are aligned to "current_period_ends_at" and "current_term_ends_at", respectively.
Subscription#Cancel has been updated to accept the "timeframe" parameter. It accepts values of BillDate or TermEnd.
> Terms timeframe enum change

- History.md
- Library/Properties/AssemblyInfo.cs
- dist/recurly.nuspec
Release 1.17.0
- Add Item class (https://github.com/recurly/recurly-client-net/pull/461)
This brings us up to API version 2.24. There is one breaking change.
- Adjustment#TaxExempt has been converted to nullable.
> Release 1.17.0

- Recurly.Tests/Errors/ApiErrorTest.cs
- Recurly/Errors/ApiError.cs
- Recurly/Errors/ApiErrors.cs
Resolves #453
We need to use ErrorMayHaveTransaction on Errors.
Here's how I tested this:
```csharp
var accountCode = Guid.NewGuid().ToString();
try
{
var purchaseReq = new PurchaseCreate()
{
Currency = "USD",
Account = new AccountPurchase()
{
Code = accountCode,
FirstName = "Benjamin",
LastName = "Du Monde",
BillingInfo = new BillingInfoCreate()
{
FirstName = "Benjamin",
LastName = "Du Monde",
Address = new Address()
{
City = "New Orleans",
Region = "LA",
Country = "US",
PostalCode = "70115",
Street1 = "900 Camp St."
},
// Evoke 3ds error: https://docs.recurly.com/docs/test#section-4000000000003220
Number = "4000000000003220",
Cvv = "123",
Month = "10",
Year = "2022"
}
},
// add subscriptions or line items to this purchase
LineItems = new List<LineItemCreate>()
{
new LineItemCreate() { …
```
> Properly handle TransactionErrors

- Recurly.Tests/Errors/ApiErrorTest.cs
This was missed because the spec that was used to originally develop the enum support did not include the error types.
> Fixing error factory bug

- Test/ItemTest.cs
- Added `[RecurlyFact(TestEnvironment.Type.Integration)]` where it had been previously left out, causing tests not to run at all.
> Repair broken tests

- Library/Purchase.cs
- Test/BaseTest.cs
- Test/PurchaseTest.cs
- Test/Recurly.Test.csproj
- Add capture function to Purchase object
- Add cancel function to Purchase object
- Create PurchaseTest to check new functions
To capture purchase:
```
var account = Accounts.Get("account_code");
var currency = "USD";
var plan = Plans.Get("plan_code");
var purchase = new Purchase(account.AccountCode, currency);
var sub = new Subscription(plan.PlanCode);
purchase.Subscriptions.Add(sub);
var previewCollection = Purchase.Authorize(purchase);
var transactionUuid = previewCollection.ChargeInvoice.Transactions[0].Uuid;
var capturedCollection = Purchase.Capture(transactionUuid);
```
To cancel purchase:
```
var account = Accounts.Get("account_code");
var currency = "USD";
var plan = Plans.Get("plan_code");
var purchase = new Purchase(account.AccountCode, currency);
var sub = new …
```
> Add 'capture' and 'cancel' to Purchase

- Library/Adjustment.cs
- Test/AdjustmentTest.cs
To fetch `external_sku`:
```csharp
var adjustment = account.NewAdjustment("USD", 5000);     
adjustment.ItemCode = 'item_code';                
adjustment.StartDate = new DateTime(2019, 6, 11);
adjustment.EndDate = new DateTime(2045, 7, 11);
adjustment.Create();
System.Console.WriteLine("Adjustment created: " + adjustment.ExternalSku);
```
> Add external_sku to Adjustment

- .gitignore
- Recurly.Tests/UtilsTest.cs
- Fixes a unit test that fails locally when not in UTC.
- Adds a float specification to the object added to the Dictionary.
- .gitignore updates to not checking build packages or Rider IDE files.
> Fix a DateTime Unit Tests when not in UTC

- History.md
- Library/Properties/AssemblyInfo.cs
- dist/recurly.nuspec
This brings us up to API version 2.25. There are no breaking changes.
- Add ConvertTrial() to Subscription (https://github.com/recurly/recurly-client-net/pull/480)
> Release 1.17.2

- Library/AddOn.cs
- Library/List/SubscriptionAddOnList.cs
- Library/SubscriptionAddOn.cs
To create subscription with tiered-pricing add-on:
```c#
var addon = plan.NewAddOn("tiered-add-on", "Tiered Add-On"); // add-on code, name
addon.TierType = "tiered";
var tier = new Tier();
tier.UnitAmountInCents.Add("USD", 123);
tier.EndingQuantity = 60;
addon.Tiers.Add(tier);
var anotherTier = new Tier();
anotherTier.UnitAmountInCents.Add("USD", 80);
addon.Tiers.Add(anotherTier);
addon.Create();
var subscription = new Subscription(account, plan, "USD"); // account, plan, currency
subscription.AddOns.Add(plan.GetAddOn(addon.AddOnCode), addon.TierType); // addon, tier type, quantity (optional, defaults to 1)
subscription.Create();
```
> Add tier_type to SubscriptionAddOn and related constructor

- Library/BillingInfo.cs
- Library/Configuration/Settings.cs
- Test/BillingInfoTest.cs
This feature is to allow support of the IBAN field in our V2 API for the applicable endpoints. This field is most similar to banking account information or credit card information, and is used to make payments for SEPA transactions.
IBAN numbers can be set in all endpoints that support BillingInfo:
PUT "/v2/accounts/{account_id}/billing_info"
PUT "/v2/accounts/{account_id}"
POST "/v2/accounts"
POST "/v2/subscriptions"
POST "/v2/purchases"
POST "/v2/purchases/preview"
A sample request payload is provided below:
```
<billing_info>
<iban>IBANNUMBERHERE</iban>
<name_on_account>Verena Example</name_on_account>
<!-- address fields... ->
</billing_info>
```
> Add IBAN attribute to BillingInfo

- Library/BillingInfo.cs
A mandate reference is a specific ID used in a payment system to show that an agreement was made between the customer and the merchant. It is often required for compliance reasons to display when a billing info is created or a payment is created.
> Add mandate_reference attribute to BillingInfo

- History.md
- Library/Properties/AssemblyInfo.cs
- dist/recurly.nuspec
This brings us up to API version 2.26. There are no breaking changes.
- Add IBAN attribute to BillingInfo [PR](https://github.com/recurly/recurly-client-dotnet/pull/490)
- Tiered Pricing [PR](https://github.com/recurly/recurly-client-dotnet/pull/496)
- Add tier_type to SubscriptionAddOn and related constructor [PR](https://github.com/recurly/recurly-client-dotnet/pull/497)
- Add mandate_reference attribute to BillingInfo [PR](https://github.com/recurly/recurly-client-dotnet/pull/499)
> Release 1.17.3

- Library/AddOn.cs
- Create separate serializer that excludes `unit_amount_in_cents` in request body
To update tiered add-on:
```c#
addon.UnitAmountInCents["USD"] = 678;
addon.Update();
```
> Allow tiered add-ons to be updated

- Library/AddOn.cs
- Library/Configuration/Settings.cs
- Library/Plan.cs
- Test/PlanTest.cs
To create item-backed add-on:
```c#
var addon = plan.NewAddOn("item_code");
addon.UnitAmountInCents.Add("USD", 200);
addon.Create();
```
To get an item-backed-add-on:
```c#
plan.GetAddOn(item.ItemCode);
```
To update item-backed add-on:
```c#
addon.UnitAmountInCents["USD"] = 200;
addon.Update();
```
When add-on has an associated item, only the following attributes are updatable:
```c#
unit_amount_in_cents
default_quantity
display_quantity_on_hosted_page
optional
```
> Enable item-backed add-ons

- History.md
- Library/Properties/AssemblyInfo.cs
- dist/recurly.nuspec
- Enable item-backed add-ons [PR](https://github.com/recurly/recurly-client-dotnet/pull/489)
- Allow tiered add-ons to be updated [PR](https://github.com/recurly/recurly-client-dotnet/pull/503)
> Release 1.17.4

- README.md
- Recurly.Tests/PagerTest.cs
- Recurly/BaseClient.cs
- Recurly/Pager.cs
Adds the `First` and `Count` methods to the `Pager` class.
The `First` method will perform a request to the API with the `limit` set to 1 and will only return the first result from the server.
The `Count` method will perform a `HEAD` request to the API for the appropriate endpoint. The value of the response header, `recurly-total-records`, will be returned. This is the total number of records that will be returned by the pager.
> Adding #First and #Count methods to Pager

- .bumpversion.cfg
- Recurly/Recurly.csproj
[Full Changelog](https://github.com/recurly/recurly-client-dotnet/compare/3.4.1...HEAD)
- Tue Apr 14 20:22:18 UTC 2020 Upgrade API version v2019-10-10 [\#505](https://github.com/recurly/recurly-client-dotnet/pull/505) ([bhelx](https://github.com/bhelx))
- Adding \#First and \#Count methods to Pager [\#491](https://github.com/recurly/recurly-client-dotnet/pull/491) ([douglasmiller](https://github.com/douglasmiller))
- CreateAccountAsync\(\) does not permit first\_name, last\_name [\#402](https://github.com/recurly/recurly-client-dotnet/issues/402)
- Included the to-be released changes in the changelog [\#504](https://github.com/recurly/recurly-client-dotnet/pull/504) ([douglasmiller](https://github.com/douglasmiller)) …
> Release 3.5.0

- Recurly.Tests/BaseClientTest.cs
- Recurly/BaseClient.cs
Adding a validation method that will ensure that path parameters are not empty strings to address issues where a `get_*` operation (`/resources/{resource_id}`) does not get handled by the API as a `list_*` operations (`/resources/`).
> Ensure that path parameters are not empty strings

- Recurly/Resources/Transaction.cs
Fixes a parsing bug when the unstructured objects in JSON have nested objects:
```
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path 'charge_invoice.transactions[0].gateway_response_values.card_country', line 1, position 3686
```
As this is a bugfix and not working as intended, we are considering releasing this as a patch level change even though it technically may require changes on the programmer's end. The scope should just be limited to the`Transaction#GatewayResponseValues` property so we cause as little disruption to existing use as possible.
In v4 we should consider switching these dynamic objects into something that the framework supports as Dictionaries are pretty cumbersome in csharp. Perhaps this object: …
> Bugfix: Unexpected character encountered while parsing value: "{"

- .bumpversion.cfg
- Recurly/Recurly.csproj
[Full Changelog](https://github.com/recurly/recurly-client-dotnet/compare/3.5.0...HEAD)
- Bugfix: Unexpected character encountered while parsing value: "{" [\#512](https://github.com/recurly/recurly-client-dotnet/pull/512) ([bhelx](https://github.com/bhelx))
- Upgrade test deps [\#511](https://github.com/recurly/recurly-client-dotnet/pull/511) ([bhelx](https://github.com/bhelx))
- Encode forward slashes in URL parameters [\#510](https://github.com/recurly/recurly-client-dotnet/pull/510) ([douglasmiller](https://github.com/douglasmiller))
- Ensure that path parameters are not empty strings [\#509](https://github.com/recurly/recurly-client-dotnet/pull/509) ([douglasmiller](https://github.com/douglasmiller))
> Release 3.5.1

- Recurly/Pager.cs
Fixes an issue where the `Next` url was not being set when using the `FetchNextPageAsync` method of a `Pager`.
> Setting Next in Pager.Build to fix async pager requests

- Recurly.Tests/BaseClientTest.cs
- Recurly.Tests/ClientTest.cs
- Recurly.Tests/Errors/ApiErrorTest.cs
- Recurly.Tests/JsonSerializerTest.cs
- Recurly.Tests/MockClient.cs
- Recurly.Tests/PagerTest.cs
- Recurly.Tests/UtilsTest.cs
- Recurly/BaseClient.cs
- Recurly/Client.cs
- Recurly/Errors/ApiErrors.cs
- Recurly/FileSerializer.cs
- Recurly/JsonSerializer.cs
- Recurly/Pager.cs
- Recurly/Utils.cs
Refactoring tests to use a standard `MockClient` that has enhanced capabilities for mocking `RestSharp` components.
> Adding MockClient and refactoring tests to use it

- Recurly.Tests/BaseClientTest.cs
- Recurly/BaseClient.cs
Query parameters were not being applied to the url properly when generating the request.
> Applying query params to url before creating the request

- Library/AddOn.cs
- Test/AddOnTest.cs
**For item-backed QBP add-ons:**
This PR changes the [serializer for item-backed add-ons](https://ci-master.dev-inf.recurly.net/blue/organizations/jenkins/recurly-github%2Frecurly-app/detail/PR-15610-head/5/pipeline) to include quantity-based pricing tiers. 
**For general QBP add-ons:**
A previous [PR](https://github.com/recurly/recurly-client-dotnet/pull/503/files) considered cases where `TierType == flat`. This allows us to update add-ons by only including the `unit_amount_in_cents ` element in the absence of QBP. Otherwise, `unit_amount_in_cents` is [included within `Tier`](https://github.com/recurly/recurly-client-net/blob/f8ca4960b4b70570bddd559f70d3117f8f1bfc6d/Library/Tier.cs#L81-L83).
To handle the case where the user may not explicitly set `TierType` to `flat` when creating an …
> Update serializer for item-backed add-ons to accommodate QBP

- Recurly.Tests/BaseClientTest.cs
- Recurly.Tests/MockClient.cs
- Recurly.Tests/PagerTest.cs
- Recurly.Tests/RequestOptionsTest.cs
- Recurly/BaseClient.cs
- Recurly/Client.cs
- Recurly/Pager.cs
- Recurly/RequestOptions.cs
Defining the `RequestOptions` class and adding it as an optional parameter to each of the client operations. This will make it possible to pass custom headers (`AddHeader(key, value)`) to be included with individual requests.
The `RequestOptions` class currently provides the `AcceptLanguage` property with a setter and getter to facilitate setting the `Accept-Language` header. This is a shorthand version of `AddHeader("Accept-Language", value)`.
Additional properties will likely be added in the future as necessary.
Example usage:
```dotnet
var accountReq = new AccountCreate()
{
// ...
};
var options = new RequestOptions {
AcceptLanguage = "fr"
};
Account account = client.CreateAccount(accountReq, options);
```
> Adding RequestOptions to facilitate passing custom request headers

- Library/Subscription.cs
- Test/SubscriptionTest.cs
Adds the timeframe query params for the [cancel subscription endpoint](https://dev.recurly.com/docs/cancel-subscription).
> Add timeframe query params to cancel subscription endpoint

- Recurly.Tests/PagerTest.cs
- Recurly/BaseClient.cs
- Recurly/Pager.cs
Updating the `Pager` class to fix issues related to the application of query parameters. This update makes use of the `BaseClient`'s query parameter handling functionality, therefore reducing the number of code paths that deal with query parameters.
Resolves #531
> Fixing query parameter handling in the Pager class

- Recurly/Client.cs
Fixing bug in latest release that resulted in an ambiguous call when using async methods.
When adding the ability to specify `RequestOptions` to the operations, an overloaded method was added for each of the `*Async` operations to facilitate providing a value for the `options` variable while excluding the `cancellationToken`. 
```c#
// Primary method will full arity
public Task<Account> CreateAccountAsync(
AccountCreate body,
CancellationToken cancellationToken = default(CancellationToken),
RequestOptions options = null
)
{
// Full implementation
}
// Overloaded method with lesser arity
public Task<Account> CreateAccountAsync(
AccountCreate body,
RequestOptions options = null
)
{
// Invoke the primary method with the default CancellationToken
CreateAccountAsync(body, …
```
> Removing overloaded Async operation methods

- Test/SubscriptionTest.cs
Regarding `Recurly.Test.SubscriptionTest.ConvertTrialWith3dsToken`, repair failing test to instead anticipate validation exception
> Expect validation exception when converting trial with fake token

- Library/Configuration/Settings.cs
- Library/List/SubscriptionAddOnList.cs
- Library/Plan.cs
- Library/SubscriptionAddOn.cs
- Test/List/SubscriptionAddOnListTest.cs
This PR adds support for items on subscriptions, where merchants may now associate a subscription add-on with an item in their catalog.
`allow_any_item_on_subscriptions` has been added to the `Plan` class. It is used to determine whether items can be assigned as add-ons to individual subscriptions. If `true`, items can be assigned as add-ons to individual subscription add-ons. If `false`, only plan add-ons can be used.
`add_on_source`, added to the `SubscriptionAddOn` class, is used to determine where the associated add-on data is pulled from. If this value is set to `plan_add_on` or left blank, then add-on data will be pulled from the plan's add-ons. If the associated  `plan` has `allow_any_item_on_subscriptions` set to `true` and this field is set to `item`, then the associated add-on …
> Support items on subscriptions

- History.md
- Library/Properties/AssemblyInfo.cs
- dist/recurly.nuspec
This brings us up to API version 2.27. There are no breaking changes.
- Update serializer for item-backed add-ons to accommodate QBP https://github.com/recurly/recurly-client-dotnet/pull/515
- Add timeframe query params to cancel subscription endpoint https://github.com/recurly/recurly-client-dotnet/pull/525
- BACS support https://github.com/recurly/recurly-client-dotnet/pull/528
- Repair test to expect a validation exception https://github.com/recurly/recurly-client-dotnet/pull/529
- Expect validation exception when converting trial with fake token https://github.com/recurly/recurly-client-dotnet/pull/530
- Support items on subscriptions https://github.com/recurly/recurly-client-dotnet/pull/539
> Release 1.17.5

- Library/BillingInfo.cs
- Test/BillingInfoTest.cs
Completed:
- Added `bsb_code` field
- Included test
Affects the following endpoints:
- `PUT /v2/accounts/{account_id}/billing_info`
- `PUT /v2/accounts/{account_id}`
- `POST /v2/accounts`
- `POST /v2/purchases`
- `POST /v2/purchases/preview`
- `POST /v2/subscriptions`
To create billing_info with BECS:
```c#
info.NameOnAccount = "Account Name";
info.City = "Adelaide";
info.Country = "AU";
info.PostalCode = "W1K 6AH";
info.AccountNumber = "11223311";
info.BsbCode = "082-082";
info.Type = "becs";
info.Create();
```
> BECS support

- History.md
- Library/BillingInfo.cs
- Library/Configuration/Settings.cs
- Library/Properties/AssemblyInfo.cs
- Test/BillingInfoTest.cs
- dist/recurly.nuspec
This brings us up to API version 2.28. There are no breaking changes.
- BECS support https://github.com/recurly/recurly-client-dotnet/pull/552
> Release 1.17.6

- README.md
- Recurly.Tests/BaseClientTest.cs
- Recurly.Tests/MockClient.cs
- Recurly.Tests/ResponseTest.cs
- Recurly/BaseClient.cs
- Recurly/Client.cs
- Recurly/EmptyResource.cs
- Recurly/Errors/ApiErrors.cs
- Recurly/Pager.cs
- Recurly/Resource.cs
- Recurly/Response.cs
The Response class is used to expose information about the response from Recurly API to the developer.
- The `Headers` property contains a List containing all of the response headers as Parameter objects.
- The `StatusCode` property contains the `HttpStatusCode` for the response.
- The `RawResponse` property contains the raw json response as a string.
> Adding Response class to Resource

- Recurly/Errors/ApiErrors.cs
- Recurly/IClient.cs
Resolves #527 
The goal here was to simply supply the `IClient` interface and have the `Client` implement it. But not force the programmer to use it anywhere. It's just available if the programmer wants to use it in testing or DI.
> Adds IClient interface and makes Client implement it

- Recurly.Tests/HttpTest.cs
- Recurly/BaseClient.cs
- Recurly/Http.cs
- Recurly/Resource.cs
This namespaces the `Response` and `Header` classes from #549 
It will also be used to house `Request` (which conflicts with Recurly.Request). Request will be added in a follow up PR.
This technically would be a breaking change but we have not released changes from #549 yet so it's safe.
> Namespaces Response and Header

- Library/AddOn.cs
Addresses issue where `usage_percentage` is parsed with nil value.
```
System.FormatException: Input string was not in a correct format.
at System.Number.ParseSingle(ReadOnlySpan`1 value, NumberStyles options, NumberFormatInfo numfmt)
at System.Single.Parse(String s, NumberStyles style, IFormatProvider provider)
at System.Xml.XmlConvert.ToSingle(String s)
at System.Xml.XmlReader.ReadElementContentAsFloat()
at Recurly.AddOn.ReadXml(XmlTextReader reader)
```
There are two previous PRs that address the issue of when <usage_percentage> is null: [one](https://github.com/recurly/recurly-client-dotnet/pull/376) for `SubscriptionAddOn` and [one](https://github.com/recurly/recurly-client-dotnet/pull/169) for `Usage`. This PR applies to `AddOn`.
> Account for when usage_percentage is null

- Library/BillingInfo.cs
Allows merchants to specify individual tax identifiers for customers (CPF + Brazil support) when creating and updating billing information.
Two fields introduced:
`tax_identifier`
`tax_identifier_type`
Example code:
```c#
info.FirstName = "Rotini";
info.LastName = "Du Monde";
info.City = "New Orleans";
info.State = "LA";
info.PostalCode = "70212";
info.CreditCardNumber = "4111111111111111";
info.ExpirationMonth = 10;
info.ExpirationYear = 2046;
info.TaxIdentifier = "758.356.352-65";
info.TaxIdentifierType = "cpf";
info.Create();
```
> Add tax identifier fields to billing info

- Recurly/Client.cs
- Recurly/IClient.cs
Returning the `Empty` response object over `void` so the programmer can get at the response metadata. This breaks the contract for `IClient` so if anyone has implemented that interface, they will need to change it to return an `EmptyResource`.
This is technically a breaking change and should be called out in the release notes.
> Return EmptyResource

- Library/BillingInfo.cs
Cleaned up some xml writers.
It makes sense to replace
```c#
if (!AccountNumber.IsNullOrEmpty())
{
xmlWriter.WriteElementString("account_number", AccountNumber);
}
```
with `xmlWriter.WriteStringIfValid("account_number", AccountNumber);` because
```c#
public static void WriteStringIfValid(this XmlWriter writer, string localName, string value)
{
if (!value.IsNullOrEmpty())
writer.WriteElementString(localName, value);
}
```
> Apply level of abstraction to xml writers by using WriteStringIfValid()

- Library/BillingInfo.cs
Reported issue:
The Address2 field in the BillingInfo object cannot be cleared by sending an empty string ("").
```c#
var account = Accounts.Get("account_code");
info.Address2 = ""; // Does not clear Address2
info.Update();
```
> Write xml for address2 field as long as it is not null

- History.md
- Library/BillingInfo.cs
- Library/Configuration/Settings.cs
- Library/Properties/AssemblyInfo.cs
- dist/recurly.nuspec
This PR merges v2.29 features into v2 branch for release and bumps the client library version to 1.17.7.
---
This brings up to API version 2.29. There are no breaking changes.
- Account for when usage_percentage is null https://github.com/recurly/recurly-client-dotnet/pull/559 (merged into v2 branch)
- Add tax identifier fields to billing info https://github.com/recurly/recurly-client-dotnet/pull/563
- Apply level of abstraction to xml writers by using WriteStringIfValid() https://github.com/recurly/recurly-client-dotnet/pull/564 (merged into v2 branch)
- Write xml for address2 field as long as it is not null https://github.com/recurly/recurly-client-dotnet/pull/566 (merged into v2 branch)
> Release 1.17.7

- Recurly.Tests/Fixtures.cs
- Recurly.Tests/JsonSerializerTest.cs
- Recurly/Errors/ApiErrors.cs
- Recurly/RecurlyStringEnumConverter.cs
This is an update for the `4.x` version of the client.
Unknown enum deserialization was failing when an enum value was Nullable. This fix finds the underlying type that the Nullable is wrapping where applicable.
> Fixes deserialization of unknown enum values

- Recurly/Client.cs
- Recurly/Errors/ApiErrors.cs
- Recurly/IClient.cs
- Recurly/Resources/AddOn.cs
- Recurly/Resources/AddOnCreate.cs
- Recurly/Resources/AddOnUpdate.cs
- Recurly/Resources/Item.cs
- Recurly/Resources/ItemCreate.cs
- Recurly/Resources/ItemUpdate.cs
- Recurly/Resources/LineItem.cs
- Recurly/Resources/LineItemCreate.cs
- Recurly/Resources/Plan.cs
- Recurly/Resources/PlanCreate.cs
- Recurly/Resources/PlanUpdate.cs
- Recurly/Resources/ShippingPurchase.cs
- Recurly/Resources/SubscriptionChangeCreate.cs
- openapi/api.yaml
**This update introduces a potentially breaking change to the `ListUsage` method.**
A new parameter, `ids`, was introduced in Recurly API and the code generation process inserts this method parameter into the middle of the existing parameters. **This will NOT be a breaking change if you are using `Named Arguments`.**
- Adds the ability to filter Subscription Add-On Usage Records by `ids` on the list endpoint
- Adds Avalara support
> Fri Aug 21 16:21:53 UTC 2020 Upgrade API version v2019-10-10

- Recurly.Tests/BaseClientTest.cs
- Recurly/BaseClient.cs
- Recurly/Errors/ApiErrors.cs
- Recurly/Errors/Factory.cs
Non-breaking update to error classes to give them a hierarchical structure. This will facilitate differentiating between a `Error.Client` error and a `Errors.Server` error for example.
New error classes have also been added to be parent classes for some existing errors (e.g. `Errors.Forbidden` error is a new class and both `Errors.InvalidApiKey` error and `Errors.InvalidPermissions` error extend it).
Most importantly, this update allows the client library to gracefully handle non-json errors in the rare occasions when they occur. These errors will be based on the HTTP status code of the response and will fall back to the existing ApiError if there is not a defined mapping.
> Adding hierarchical errors and moving the error factory

- Library/BillingInfo.cs
- Library/Recurly.csproj
- Library/VerifyBillingInfo.cs
- Library/VerifyGateway.cs
- Test/BillingInfoTest.cs
If the account has billing information for anything other than a credit card, this will return 422, with an appropriate error message. If successful, this will return 200, with the transaction's data.
`gateway_code` (optional) is the code for the gateway to use for the verification. If unspecified, a gateway will be selected using the normal rules.
Example
```c#
// verify without specifying gateway code to use 
billingInfo.Verify()
// verify with a specific gateway code
billingInfo.Verify("gateway-code")
```
> New endpoint to verify an account's billing information

- History.md
- Library/BillingInfo.cs
- Library/Properties/AssemblyInfo.cs
- Library/Recurly.csproj
- Library/VerifyBillingInfo.cs
- Test/BillingInfoTest.cs
- dist/recurly.nuspec
This PR merges new features into the v2 branch for release and bumps the dotnet client library version to 1.17.8.
------
- New endpoint to verify an account's billing information https://github.com/recurly/recurly-client-dotnet/pull/577
> Release 1.17.8

- Recurly.Tests/PagerTest.cs
- Recurly/BaseClient.cs
- Recurly/Http.cs
- Recurly/Pager.cs
According to section 4.2 of [RFC 2616](https://www.ietf.org/rfc/rfc2616.txt):
> Each header field consists of a name followed by a colon (":") and the field value. Field names are case-insensitive.
This update will make the client treat headers in a case-insensitive manner.
The `Recurly.Http.Response` class has also been updated to expose the `GetHeader` method.
> Updating client to be compliant with RFC 2616: case-insensitive headers

- .bumpversion.cfg
- Recurly/Recurly.csproj
[Full Changelog](https://github.com/recurly/recurly-client-dotnet/compare/3.13.0...HEAD)
- Updating client to be compliant with RFC 2616: case-insensitive headers [\#581](https://github.com/recurly/recurly-client-dotnet/pull/581) ([douglasmiller](https://github.com/douglasmiller))
> Release 3.13.1

- Recurly.Tests/BaseClientTest.cs
- Recurly/BaseClient.cs
Add a test case to verify that unknown error types are thrown as `ApiError`. I'm testing for the desired behavior [by way of `ArgumentException`](https://github.com/recurly/recurly-client-dotnet/blob/master/Recurly/Errors/Factory.cs#L189) which feels wonky. I'm open to any suggestions for a better way to work around [strict mode](https://github.com/recurly/recurly-client-dotnet/blob/master/Recurly/Utils.cs#L11) at test time to allow a more direct test.
See related [#640 in recurly-client-ruby](https://github.com/recurly/recurly-client-ruby/issues/640) and [#369 in recurly-client-python](https://github.com/recurly/recurly-client-python/issues/369) for context.
> Add test coverage for unknown error types

- Library/Coupon.cs
- Test/CouponTest.cs
Add `item_codes` and `applies_to_all_items` to Coupon
Example
```c#
var coupon = new Coupon(
"special",
"Special", 
new Dictionary<string, int>() { { "USD", 200 } }
);
// `applies_to_all_items` defaults to false, so next line is optional
coupon.AppliesToAllItems = false;
coupon.Items.Add("one_item");
coupon.Items.Add("two_item");
coupon.Create();
```
> Support item-specific coupons

- History.md
- Library/Properties/AssemblyInfo.cs
- dist/recurly.nuspec
- Bump to dotnet client library version 1.17.9 
- Update history
-----
- Support item-specific coupons https://github.com/recurly/recurly-client-dotnet/pull/588
> Release 1.17.9

- Library/AddOn.cs
- Library/BillingInfo.cs
- Because `item_state` and `external_sku` are included in the xml response for item-based add-ons, it would be good practice to expose this fields to the programmer.
- Same applies to `last_two` for `BillingInfo`
> Expose fields in response xml to developer

- Recurly/Client.cs
- Recurly/IClient.cs
- Recurly/Resources/Subscription.cs
- openapi/api.yaml
- Adds the `state` parameter to the `ListAccountCouponRedemptions` operation.
- Adds the `charge` parameter to the `TerminateSubscription` operation so that a merchant can choose to not bill a customer for un-billed usage when terminating a subscription
> Latest Changes for 2019-10-10

- Library/BillingInfo.cs
- Library/Extensions/StringExtensions.cs
- Test/BillingInfoTest.cs
- Test/TestCreditCardNumbers.cs
- Add UnionPay as CreditCardType enum in BillingInfo class
- Include tests
> Add missing UnionPay enum to BillingInfo

- Library/Recurly.csproj
- Library/SubscriptionAddOn.cs
- Library/SubscriptionAddOnTier.cs
- Test/Recurly.Test.csproj
- Test/SubscriptionAddOnTest.cs
- Create SubscriptionAddOnTier class to allow updating, where UnitAmountInCents is an integer, not a dictionary of strings and integers
- Update SubscriptionAddOn class to use SubscriptionAddOnTier, not Tier
- Create tests for SubscriptionAddOn
Though it would be more simple to have one Tier class, subscription-based add-on tiers are different from plan add-on tiers in that `unit_amount_in_cents` must be an integer for the former and a dictionary of currencies and values for the latter. Therefore SubscriptionAddOnTier is a required class if we want to be able to update quantity-based subscription add-ons.
Addresses https://github.com/recurly/recurly-client-dotnet/pull/561
Example:
```c#
var subscription = Subscriptions.Get("44f83d7cba354d5b84812419f923ea96");
var change = new …
```
> Repair PUT /subscriptions/:subscription_id

- Library/CreditPayment.cs
- Test/CreditPaymentTest.cs
- Test/PurchaseTest.cs
- Test/Recurly.Test.csproj
- Correct request url from /credit_payment/ to /credit_payments/
- Fix AmountInCents attribute, which was previously included as UnitAmountInCent
- Added test for credit payments
Previous calls to [GET /credit_payments/{uuid}](https://developers.recurly.com/api-v2/v2.29/index.html#operation/lookupCreditPayment) would fail due to incorrect request url. Simply adding an 's' resolves the issue
> Repair Lookup Credit Payment endpoint

- README.md
- Recurly.Tests/BaseClientTest.cs
- Recurly/BaseClient.cs
Given that the unit tests mock the HTTP client at the RestSharp interface level, I was unable to automate validation of the timeout functionality. A simple test has been added to verify that the property can be initialized and read back.
I did however modify some playground scripts and manually confirm that it was behaving as expected.
In the past, I've verified configured timeouts by making a real HTTP connection to a debug server launched by the test runner. Unclear how to approach that in this repo as:
1. overriding the endpoint URL at test time is tricky
2. unclear if a barebones Kestrel server can be raised at test time
Open to suggestions for improvement.
> Expose HTTP timeout for Recurly.BaseClient

- History.md
- Library/Properties/AssemblyInfo.cs
- dist/recurly.nuspec
- Bump to dotnet client library version 1.17.10
- Update history
-----
- Fix test: create billing info (IBAN) https://github.com/recurly/recurly-client-dotnet/pull/592
- Expose fields in response xml to developer https://github.com/recurly/recurly-client-dotnet/pull/593
- Repair Lookup Credit Payment endpoint https://github.com/recurly/recurly-client-dotnet/pull/602
- Repair PUT /subscriptions/:subscription_id https://github.com/recurly/recurly-client-dotnet/pull/604
- Add missing UnionPay enum to BillingInfo https://github.com/recurly/recurly-client-dotnet/pull/605
> Bump to dotnet client library version 1.17.10 and update history

- Recurly.Tests/UtilsTest.cs
- Recurly/Utils.cs
An extension of #471 which added Enum support. Query string parameters were not properly using the EnumMember Value annotation when generating the request.
> Convert query string enums to their EnumMember Value

- .github_changelog_generator
- scripts/build
Internal only update to ignore issues and pull requests with the `internal` label from changelog generation.
> Ignoring 'internal' tags in changelog generation

- .bumpversion.cfg
- Recurly/Recurly.csproj
[Full Changelog](https://github.com/recurly/recurly-client-dotnet/compare/4.0.0...HEAD)
- Generated Latest Changes for v2021-02-25 [\#621](https://github.com/recurly/recurly-client-dotnet/pull/621) ([recurly-integrations](https://github.com/recurly-integrations))
- Sync updates not ported from 3.x client [\#618](https://github.com/recurly/recurly-client-dotnet/pull/618) ([douglasmiller](https://github.com/douglasmiller))
- Expose HTTP timeout for Recurly.BaseClient [\#608](https://github.com/recurly/recurly-client-dotnet/pull/608) ([jguidry-recurly](https://github.com/jguidry-recurly))
> Release 4.0.1

- scripts/release
Removing dependence on an environment variable to determine the current version and adding a guard statement for the `NUGET_TOKEN`.
> Updating release script to be more defensive
